import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SEED_HASH = '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'; // "SeedPass@1"

const companies = [
  {
    email: 'seed.techcorp@hiralent.dev',
    full_name: 'TechCorp Hiring',
    company_name: 'TechCorp Solutions',
    display_name: 'TechCorp',
    industry: 'Technology',
    company_size: 'medium',
    headquarters: 'Casablanca, Morocco',
    description: 'A leading technology company building software solutions for the MENA region.',
    logo_url: 'https://ui-avatars.com/api/?name=TechCorp&background=2563EB&color=fff&size=128',
    remote_policy: 'hybrid',
  },
  {
    email: 'seed.innovate@hiralent.dev',
    full_name: 'Innovate Hub Hiring',
    company_name: 'Innovate Hub',
    display_name: 'Innovate Hub',
    industry: 'FinTech',
    company_size: 'startup',
    headquarters: 'Rabat, Morocco',
    description: 'FinTech startup disrupting payment infrastructure across Africa.',
    logo_url: 'https://ui-avatars.com/api/?name=Innovate+Hub&background=7C3AED&color=fff&size=128',
    remote_policy: 'fully_remote',
  },
  {
    email: 'seed.globaltech@hiralent.dev',
    full_name: 'GlobalTech Hiring',
    company_name: 'GlobalTech International',
    display_name: 'GlobalTech',
    industry: 'Consulting',
    company_size: 'large',
    headquarters: 'Dubai, UAE',
    description: 'International consulting firm with offices across Europe, Middle East, and Africa.',
    logo_url: 'https://ui-avatars.com/api/?name=GlobalTech&background=059669&color=fff&size=128',
    remote_policy: 'office_only',
  },
];

const jobsData = [
  // ── TechCorp (index 0) ─────────────────────────────────────────────────────
  {
    companyIndex: 0,
    title: 'Senior Frontend Developer',
    location: 'Casablanca, Morocco',
    description: 'We are looking for a Senior Frontend Developer to join our team and build scalable web applications. You will work closely with our product and design teams to deliver exceptional user experiences.',
    salary_range: '25,000 – 35,000 MAD/month',
    required_skills: ['React', 'TypeScript', 'Next.js', 'TailwindCSS', 'GraphQL', 'Jest'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'hybrid',
    department: 'Engineering',
    urgency_level: 'high',
  },
  {
    companyIndex: 0,
    title: 'Backend Engineer (Node.js)',
    location: 'Casablanca, Morocco',
    description: 'Join our backend team to design and implement high-performance APIs, microservices, and real-time systems. You will work with Node.js, NestJS, and PostgreSQL in a cloud-native environment.',
    salary_range: '22,000 – 32,000 MAD/month',
    required_skills: ['Node.js', 'NestJS', 'TypeScript', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'hybrid',
    department: 'Engineering',
    urgency_level: 'medium',
  },
  {
    companyIndex: 0,
    title: 'Full Stack Developer',
    location: 'Remote',
    description: 'Work on both frontend and backend systems. You will own features end-to-end, from database design to React components, collaborating with a cross-functional team.',
    salary_range: '18,000 – 28,000 MAD/month',
    required_skills: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'REST API', 'Git'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'fully_remote',
    department: 'Engineering',
    urgency_level: 'medium',
  },
  {
    companyIndex: 0,
    title: 'DevOps Engineer',
    location: 'Casablanca, Morocco',
    description: 'Manage and scale our cloud infrastructure, CI/CD pipelines, and container orchestration. Work with Kubernetes, Terraform, and AWS to ensure 99.9% uptime.',
    salary_range: '28,000 – 40,000 MAD/month',
    required_skills: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'CI/CD', 'Linux', 'Python'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'hybrid',
    department: 'Infrastructure',
    urgency_level: 'high',
  },
  {
    companyIndex: 0,
    title: 'UX/UI Designer',
    location: 'Casablanca, Morocco',
    description: 'Design beautiful, intuitive product experiences. You will create wireframes, prototypes, and design systems in Figma, and collaborate closely with engineers.',
    salary_range: '15,000 – 22,000 MAD/month',
    required_skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'hybrid',
    department: 'Design',
    urgency_level: 'low',
  },
  {
    companyIndex: 0,
    title: 'Data Analyst',
    location: 'Casablanca, Morocco',
    description: 'Analyze large datasets to extract business insights. Build dashboards and reports using SQL, Python, and BI tools. Work with product and marketing teams to drive data-informed decisions.',
    salary_range: '14,000 – 20,000 MAD/month',
    required_skills: ['SQL', 'Python', 'Pandas', 'Power BI', 'Excel', 'Statistics'],
    job_type: 'full_time',
    experience_level: 'entry',
    remote_option: 'hybrid',
    department: 'Data',
    urgency_level: 'low',
  },
  {
    companyIndex: 0,
    title: 'Product Manager',
    location: 'Casablanca, Morocco',
    description: 'Define and drive the product roadmap for our SaaS platform. Work cross-functionally with engineering, design, and marketing to ship features customers love.',
    salary_range: '25,000 – 38,000 MAD/month',
    required_skills: ['Product Strategy', 'Agile', 'Jira', 'User Stories', 'Stakeholder Management', 'Data Analysis'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'office_only',
    department: 'Product',
    urgency_level: 'medium',
  },
  {
    companyIndex: 0,
    title: 'QA Engineer',
    location: 'Remote',
    description: 'Ensure the quality of our software products by designing and executing test plans, automating tests, and collaborating with developers to resolve defects quickly.',
    salary_range: '12,000 – 18,000 MAD/month',
    required_skills: ['Selenium', 'Cypress', 'Jest', 'Postman', 'SQL', 'Bug Tracking'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'fully_remote',
    department: 'Engineering',
    urgency_level: 'low',
  },
  {
    companyIndex: 0,
    title: 'Mobile Developer (React Native)',
    location: 'Casablanca, Morocco',
    description: 'Build and maintain cross-platform mobile apps for iOS and Android using React Native. Collaborate with backend engineers and designers to create smooth mobile experiences.',
    salary_range: '20,000 – 30,000 MAD/month',
    required_skills: ['React Native', 'TypeScript', 'Redux', 'REST API', 'iOS', 'Android'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'hybrid',
    department: 'Engineering',
    urgency_level: 'medium',
  },
  {
    companyIndex: 0,
    title: 'Junior Frontend Developer (Internship)',
    location: 'Casablanca, Morocco',
    description: 'Great opportunity for final-year students or recent graduates. You will work on real features under the mentorship of senior engineers.',
    salary_range: '4,000 – 6,000 MAD/month',
    required_skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
    job_type: 'internship',
    experience_level: 'entry',
    remote_option: 'hybrid',
    department: 'Engineering',
    urgency_level: 'low',
  },

  // ── Innovate Hub (index 1) ─────────────────────────────────────────────────
  {
    companyIndex: 1,
    title: 'ML Engineer',
    location: 'Remote',
    description: 'Build and deploy machine learning models for fraud detection, credit scoring, and transaction classification in our FinTech platform.',
    salary_range: '30,000 – 45,000 MAD/month',
    required_skills: ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'MLflow', 'SQL', 'Docker'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'fully_remote',
    department: 'AI/ML',
    urgency_level: 'high',
  },
  {
    companyIndex: 1,
    title: 'Data Scientist',
    location: 'Rabat, Morocco',
    description: 'Use statistical methods and ML to extract insights from financial data. Build predictive models and A/B test experiments to improve our product.',
    salary_range: '22,000 – 35,000 MAD/month',
    required_skills: ['Python', 'R', 'Statistics', 'Machine Learning', 'SQL', 'Pandas', 'Matplotlib'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'hybrid',
    department: 'Data',
    urgency_level: 'medium',
  },
  {
    companyIndex: 1,
    title: 'Backend Developer (Python)',
    location: 'Remote',
    description: 'Build scalable REST APIs and microservices in Python/FastAPI to power our payment infrastructure. Write clean, tested code that handles millions of transactions.',
    salary_range: '20,000 – 32,000 MAD/month',
    required_skills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'Kafka'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'fully_remote',
    department: 'Engineering',
    urgency_level: 'high',
  },
  {
    companyIndex: 1,
    title: 'Blockchain Developer',
    location: 'Remote',
    description: 'Develop and audit smart contracts, DeFi protocols, and Web3 integrations for our next-generation payment products.',
    salary_range: '35,000 – 55,000 MAD/month',
    required_skills: ['Solidity', 'Web3.js', 'Ethereum', 'Hardhat', 'TypeScript', 'Smart Contracts'],
    job_type: 'contract',
    experience_level: 'senior',
    remote_option: 'fully_remote',
    department: 'Engineering',
    urgency_level: 'medium',
  },
  {
    companyIndex: 1,
    title: 'Security Engineer',
    location: 'Rabat, Morocco',
    description: 'Protect our FinTech infrastructure from threats. Conduct penetration testing, security audits, and implement best practices across our systems.',
    salary_range: '28,000 – 42,000 MAD/month',
    required_skills: ['Penetration Testing', 'OWASP', 'AWS Security', 'Python', 'Network Security', 'SIEM'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'hybrid',
    department: 'Security',
    urgency_level: 'high',
  },
  {
    companyIndex: 1,
    title: 'Product Designer',
    location: 'Remote',
    description: 'Design the end-to-end user experience for our mobile payment app used by thousands of users across Africa. From research to polished UI, you own the design.',
    salary_range: '18,000 – 28,000 MAD/month',
    required_skills: ['Figma', 'Mobile Design', 'User Research', 'Prototyping', 'Design Thinking'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'fully_remote',
    department: 'Design',
    urgency_level: 'medium',
  },
  {
    companyIndex: 1,
    title: 'Frontend Developer (Vue.js)',
    location: 'Rabat, Morocco',
    description: 'Build the dashboard and admin tools for our FinTech platform using Vue.js and TypeScript. Work in a fast-paced startup environment.',
    salary_range: '15,000 – 25,000 MAD/month',
    required_skills: ['Vue.js', 'TypeScript', 'Pinia', 'TailwindCSS', 'REST API', 'Git'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'hybrid',
    department: 'Engineering',
    urgency_level: 'low',
  },
  {
    companyIndex: 1,
    title: 'Data Engineer',
    location: 'Remote',
    description: 'Build data pipelines, ETL processes, and data warehouses to support our analytics and ML teams. Own the data infrastructure from ingestion to transformation.',
    salary_range: '25,000 – 38,000 MAD/month',
    required_skills: ['Apache Spark', 'Airflow', 'Python', 'dbt', 'BigQuery', 'Kafka', 'SQL'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'fully_remote',
    department: 'Data',
    urgency_level: 'medium',
  },
  {
    companyIndex: 1,
    title: 'Technical Lead',
    location: 'Rabat, Morocco',
    description: 'Lead a team of 5 engineers building our core payment processing engine. Define architecture, mentor engineers, and collaborate with the CTO on technical strategy.',
    salary_range: '45,000 – 65,000 MAD/month',
    required_skills: ['Node.js', 'Python', 'System Design', 'Leadership', 'Microservices', 'PostgreSQL', 'Cloud'],
    job_type: 'full_time',
    experience_level: 'executive',
    remote_option: 'hybrid',
    department: 'Engineering',
    urgency_level: 'high',
  },
  {
    companyIndex: 1,
    title: 'Junior Data Analyst (Internship)',
    location: 'Rabat, Morocco',
    description: 'Support our data team in building dashboards and analyzing FinTech metrics. Great opportunity to gain hands-on experience with real financial data.',
    salary_range: '4,500 – 6,500 MAD/month',
    required_skills: ['Excel', 'SQL', 'Python basics', 'Power BI', 'Statistics'],
    job_type: 'internship',
    experience_level: 'entry',
    remote_option: 'hybrid',
    department: 'Data',
    urgency_level: 'low',
  },

  // ── GlobalTech (index 2) ───────────────────────────────────────────────────
  {
    companyIndex: 2,
    title: 'Cloud Architect',
    location: 'Dubai, UAE',
    description: 'Design and implement enterprise cloud solutions for our international clients. Lead cloud migration projects and define cloud strategy for Fortune 500 companies.',
    salary_range: '25,000 – 45,000 AED/month',
    required_skills: ['AWS', 'Azure', 'GCP', 'Terraform', 'Kubernetes', 'Solution Architecture'],
    job_type: 'full_time',
    experience_level: 'executive',
    remote_option: 'hybrid',
    department: 'Cloud',
    urgency_level: 'high',
  },
  {
    companyIndex: 2,
    title: 'Business Analyst',
    location: 'Paris, France',
    description: 'Gather and document client requirements, bridge the gap between business and IT, and drive process improvements for our consulting engagements.',
    salary_range: '4,500 – 6,500 EUR/month',
    required_skills: ['Business Analysis', 'UML', 'Agile', 'SQL', 'Stakeholder Management', 'PowerPoint'],
    job_type: 'full_time',
    experience_level: 'mid',
    remote_option: 'hybrid',
    department: 'Consulting',
    urgency_level: 'medium',
  },
  {
    companyIndex: 2,
    title: 'Senior Java Developer',
    location: 'London, UK',
    description: 'Build enterprise-grade applications for banking and insurance clients using Java, Spring Boot, and microservices architecture.',
    salary_range: '6,000 – 8,500 GBP/month',
    required_skills: ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL', 'Kafka', 'Docker', 'JUnit'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'hybrid',
    department: 'Engineering',
    urgency_level: 'medium',
  },
  {
    companyIndex: 2,
    title: 'ERP Consultant (SAP)',
    location: 'Dubai, UAE',
    description: 'Lead SAP S/4HANA implementation and migration projects for enterprise clients. Manage stakeholders, train end-users, and ensure successful go-live.',
    salary_range: '20,000 – 35,000 AED/month',
    required_skills: ['SAP S/4HANA', 'SAP FI/CO', 'ABAP', 'Project Management', 'Business Process'],
    job_type: 'contract',
    experience_level: 'senior',
    remote_option: 'office_only',
    department: 'Consulting',
    urgency_level: 'high',
  },
  {
    companyIndex: 2,
    title: 'Cybersecurity Consultant',
    location: 'Paris, France',
    description: 'Conduct security assessments, penetration testing, and compliance audits (ISO 27001, GDPR) for enterprise clients across financial services and healthcare sectors.',
    salary_range: '5,000 – 8,000 EUR/month',
    required_skills: ['ISO 27001', 'GDPR', 'Penetration Testing', 'Risk Assessment', 'SIEM', 'Cloud Security'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'hybrid',
    department: 'Security',
    urgency_level: 'medium',
  },
  {
    companyIndex: 2,
    title: 'Project Manager (IT)',
    location: 'London, UK',
    description: 'Lead complex IT transformation projects for enterprise clients. Manage scope, budget, timeline, and cross-functional teams of 15–30 people.',
    salary_range: '5,500 – 7,500 GBP/month',
    required_skills: ['PMP', 'Agile', 'Scrum', 'Risk Management', 'MS Project', 'Stakeholder Management'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'hybrid',
    department: 'Management',
    urgency_level: 'low',
  },
  {
    companyIndex: 2,
    title: 'Data Analyst (Part-time)',
    location: 'Remote',
    description: 'Support our consulting clients with data analysis, reporting, and dashboard development on a part-time basis (3 days/week).',
    salary_range: '2,500 – 3,500 EUR/month',
    required_skills: ['SQL', 'Power BI', 'Tableau', 'Excel', 'Python', 'Data Visualization'],
    job_type: 'part_time',
    experience_level: 'mid',
    remote_option: 'fully_remote',
    department: 'Data',
    urgency_level: 'low',
  },
  {
    companyIndex: 2,
    title: 'AI/ML Consultant',
    location: 'Dubai, UAE',
    description: 'Help enterprise clients adopt AI solutions: from use-case identification and model development to production deployment and team enablement.',
    salary_range: '22,000 – 40,000 AED/month',
    required_skills: ['Machine Learning', 'Python', 'LLMs', 'Azure AI', 'Data Science', 'Consulting'],
    job_type: 'full_time',
    experience_level: 'senior',
    remote_option: 'hybrid',
    department: 'AI/ML',
    urgency_level: 'high',
  },
  {
    companyIndex: 2,
    title: 'Solution Architect',
    location: 'London, UK',
    description: 'Design end-to-end technical solutions for client engagements. Evaluate requirements, produce architecture blueprints, and guide implementation teams.',
    salary_range: '7,000 – 10,000 GBP/month',
    required_skills: ['Solution Architecture', 'Cloud', 'Microservices', 'API Design', 'Enterprise Architecture'],
    job_type: 'full_time',
    experience_level: 'executive',
    remote_option: 'hybrid',
    department: 'Architecture',
    urgency_level: 'medium',
  },
  {
    companyIndex: 2,
    title: 'Graduate Analyst (Fresh Graduate)',
    location: 'Paris, France',
    description: 'Kick-start your consulting career! Join our 18-month graduate program. You will rotate across different practices (data, cloud, security) and work on real client projects.',
    salary_range: '2,800 – 3,500 EUR/month',
    required_skills: ['Excel', 'PowerPoint', 'SQL basics', 'Communication', 'Problem Solving'],
    job_type: 'full_time',
    experience_level: 'entry',
    remote_option: 'hybrid',
    department: 'Consulting',
    urgency_level: 'low',
  },
  {
    companyIndex: 2,
    title: 'Technical Writer (Contract)',
    location: 'Remote',
    description: 'Create technical documentation, API guides, architecture diagrams, and user manuals for our consulting deliverables and internal knowledge base.',
    salary_range: '2,000 – 3,000 EUR/month',
    required_skills: ['Technical Writing', 'Markdown', 'API Documentation', 'Confluence', 'Diagrams.net'],
    job_type: 'contract',
    experience_level: 'mid',
    remote_option: 'fully_remote',
    department: 'Documentation',
    urgency_level: 'low',
  },
];

export const seedJobs = async () => {
  console.log('🏢 Seeding companies and jobs...');

  const companyIds: string[] = [];

  for (const co of companies) {
    // Upsert user
    const user = await prisma.user.upsert({
      where: { email: co.email },
      update: {},
      create: {
        email: co.email,
        full_name: co.full_name,
        password_hash: SEED_HASH,
        role: 'company_admin',
        is_email_verified: true,
      },
    });

    // Upsert company profile
    await prisma.companyProfile.upsert({
      where: { company_id: user.user_id },
      update: {},
      create: {
        company_id:    user.user_id,
        company_name:  co.company_name,
        display_name:  co.display_name,
        industry:      co.industry,
        company_size:  co.company_size,
        headquarters:  co.headquarters,
        description:   co.description,
        logo_url:      co.logo_url,
        remote_policy: co.remote_policy,
        verified:      true,
        verification_status: 'verified',
      },
    });

    companyIds.push(user.user_id);
  }

  let created = 0;
  for (let i = 0; i < jobsData.length; i++) {
    const job = jobsData[i];
    const company_id = companyIds[job.companyIndex];
    // Deterministic job_id keyed by position so re-running the seed upserts in place
    // instead of appending 31 duplicate jobs each run (idempotent demo seed).
    const job_id = `seed-job-${i}`;
    const data = {
      company_id,
      title:            job.title,
      location:         job.location,
      description:      job.description,
      salary_range:     job.salary_range,
      // required_skills is empty so any candidate can apply (skills shown in description)
      required_skills:  [],
      job_type:         job.job_type,
      experience_level: job.experience_level,
      remote_option:    job.remote_option,
      department:       job.department,
      urgency_level:    job.urgency_level,
      status:           'ACTIVE' as const,
    };
    await prisma.companyJob.upsert({
      where: { job_id },
      update: data,
      create: { job_id, ...data },
    });
    created++;
  }

  console.log(`✅ ${companies.length} companies and ${created} jobs seeded successfully`);
};
