export const industryOptions = [
  { value: 'oil_gas', label: 'Oil & Gas' },
  { value: 'petrochemicals', label: 'Petrochemicals' },
  { value: 'natural_gas', label: 'Natural Gas' },
  { value: 'lng_production', label: 'LNG Production' },
  { value: 'oilfield_services', label: 'Oilfield Services' },
  { value: 'petroleum_refining', label: 'Petroleum Refining' },
  { value: 'energy_trading', label: 'Energy Trading' },
  { value: 'construction', label: 'Construction' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'commercial_real_estate', label: 'Commercial Real Estate' },
  { value: 'residential_real_estate', label: 'Residential Real Estate' },
  { value: 'infrastructure_development', label: 'Infrastructure Development' },
  { value: 'construction_management', label: 'Construction Management' },
  { value: 'building_materials', label: 'Building Materials' },
  { value: 'tourism', label: 'Tourism' },
  { value: 'hospitality', label: 'Hospitality' },
  { value: 'hotels_resorts', label: 'Hotels & Resorts' },
  { value: 'luxury_hospitality', label: 'Luxury Hospitality' },
  { value: 'sports_tourism', label: 'Sports Tourism' },
  { value: 'eco_tourism', label: 'Eco-Tourism' },
  { value: 'travel_agency', label: 'Travel Agency' },
  { value: 'tourism_tech', label: 'Tourism Technology' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'medical_tourism', label: 'Medical Tourism' },
  { value: 'healthcare_it', label: 'Healthcare IT' },
  { value: 'medical_devices', label: 'Medical Devices' },
  { value: 'pharmaceuticals', label: 'Pharmaceuticals' },
  { value: 'clinical_research', label: 'Clinical Research' },
  { value: 'dental_services', label: 'Dental Services' },
  { value: 'mental_health_services', label: 'Mental Health Services' },
  { value: 'e_commerce', label: 'E-Commerce' },
  { value: 'retail', label: 'Retail' },
  { value: 'online_retail', label: 'Online Retail' },
  { value: 'luxury_retail', label: 'Luxury Retail' },
  { value: 'grocery_delivery', label: 'Grocery Delivery' },
  { value: 'quick_commerce', label: 'Quick Commerce' },
  { value: 'retail_tech', label: 'Retail Technology' },
  { value: 'beauty_products', label: 'Beauty Products' },
  { value: 'information_technology', label: 'Information Technology' },
  { value: 'software_development', label: 'Software Development' },
  { value: 'artificial_intelligence', label: 'Artificial Intelligence' },
  { value: 'blockchain_technology', label: 'Blockchain Technology' },
  { value: 'cybersecurity', label: 'Cybersecurity' },
  { value: 'cloud_computing', label: 'Cloud Computing' },
  { value: 'data_analytics', label: 'Data Analytics' },
  { value: 'fintech', label: 'Financial Technology (FinTech)' },
  { value: '5g_technology', label: '5G Technology' },
  { value: 'mobile_app_development', label: 'Mobile App Development' },
  { value: 'web_development', label: 'Web Development' },
  { value: 'digital_marketing', label: 'Digital Marketing' },
  { value: 'telecommunications', label: 'Telecommunications' },
  { value: 'iot_solutions', label: 'IoT Solutions' },
  { value: 'smart_city_tech', label: 'Smart City Technology' },
  { value: 'gaming_development', label: 'Gaming Development' },
  { value: 'augmented_reality', label: 'Augmented Reality' },
  { value: 'virtual_reality', label: 'Virtual Reality' },
  { value: 'banking', label: 'Banking' },
  { value: 'islamic_banking', label: 'Islamic Banking' },
  { value: 'financial_services', label: 'Financial Services' },
  { value: 'investment_management', label: 'Investment Management' },
  { value: 'private_equity', label: 'Private Equity' },
  { value: 'venture_capital', label: 'Venture Capital' },
  { value: 'insurance', label: 'Insurance' },
  { value: 'insurance_tech', label: 'Insurance Technology' },
  { value: 'financial_advisory', label: 'Financial Advisory' },
  { value: 'renewable_energy', label: 'Renewable Energy' },
  { value: 'solar_energy', label: 'Solar Energy' },
  { value: 'wind_energy', label: 'Wind Energy' },
  { value: 'green_hydrogen', label: 'Green Hydrogen' },
  { value: 'energy_storage', label: 'Energy Storage' },
  { value: 'energy_efficiency', label: 'Energy Efficiency' },
  { value: 'sustainable_energy', label: 'Sustainable Energy' },
  { value: 'logistics', label: 'Logistics' },
  { value: 'transportation', label: 'Transportation' },
  { value: 'freight_forwarding', label: 'Freight Forwarding' },
  { value: 'supply_chain_management', label: 'Supply Chain Management' },
  { value: 'logistics_tech', label: 'Logistics Technology' },
  { value: 'aviation', label: 'Aviation' },
  { value: 'aerospace', label: 'Aerospace' },
  { value: 'civil_aerospace', label: 'Civil Aerospace' },
  { value: 'defense', label: 'Defense' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'electric_vehicles', label: 'Electric Vehicles' },
  { value: 'automotive_parts', label: 'Automotive Parts' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'electronics_manufacturing', label: 'Electronics Manufacturing' },
  { value: 'semiconductor_manufacturing', label: 'Semiconductor Manufacturing' },
  { value: 'industrial_automation', label: 'Industrial Automation' },
  { value: 'chemical_manufacturing', label: 'Chemical Manufacturing' },
  { value: 'food_processing', label: 'Food Processing' },
  { value: 'textile_manufacturing', label: 'Textile Manufacturing' },
  { value: 'steel_manufacturing', label: 'Steel Manufacturing' },
  { value: 'cement_manufacturing', label: 'Cement Manufacturing' },
  { value: 'education', label: 'Education' },
  { value: 'edtech', label: 'Educational Technology' },
  { value: 'online_education', label: 'Online Education' },
  { value: 'language_training', label: 'Language Training' },
  { value: 'vocational_training', label: 'Vocational Training' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'agribusiness', label: 'Agribusiness' },
  { value: 'aquaculture', label: 'Aquaculture' },
  { value: 'organic_farming', label: 'Organic Farming' },
  { value: 'agricultural_tech', label: 'Agricultural Technology' },
  { value: 'mining', label: 'Mining' },
  { value: 'mining_tech', label: 'Mining Technology' },
  { value: 'real_estate_development', label: 'Real Estate Development' },
  { value: 'property_management', label: 'Property Management' },
  { value: 'urban_planning', label: 'Urban Planning' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'engineering_consulting', label: 'Engineering Consulting' },
  { value: 'event_management', label: 'Event Management' },
  { value: 'event_technology', label: 'Event Technology' },
  { value: 'advertising', label: 'Advertising' },
  { value: 'marketing_agency', label: 'Marketing Agency' },
  { value: 'social_media_management', label: 'Social Media Management' },
  { value: 'public_relations', label: 'Public Relations' },
  { value: 'media_production', label: 'Media Production' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'film_production', label: 'Film Production' },
  { value: 'music_production', label: 'Music Production' },
  { value: 'sports_management', label: 'Sports Management' },
  { value: 'retail_clothing', label: 'Retail Clothing' },
  { value: 'retail_electronics', label: 'Retail Electronics' },
  { value: 'retail_food', label: 'Retail Food' },
  { value: 'luxury_goods', label: 'Luxury Goods' },
  { value: 'jewelry_retail', label: 'Jewelry Retail' },
  { value: 'fashion_retail', label: 'Fashion Retail' },
  { value: 'cosmetics_retail', label: 'Cosmetics Retail' },
  { value: 'furniture_retail', label: 'Furniture Retail' },
  { value: 'home_decor', label: 'Home Decor' },
  { value: 'supermarkets', label: 'Supermarkets' },
  { value: 'on_demand_services', label: 'On-Demand Services' },
  { value: 'handyman_services', label: 'Handyman Services' },
  { value: 'pet_services', label: 'Pet Services' },
  { value: 'dog_walking', label: 'Dog Walking' },
  { value: 'security_services', label: 'Security Services' },
  { value: 'cleaning_services', label: 'Cleaning Services' },
  { value: 'facility_management', label: 'Facility Management' },
  { value: 'catering_services', label: 'Catering Services' },
  { value: 'food_delivery', label: 'Food Delivery' },
  { value: 'restaurant_services', label: 'Restaurant Services' },
  { value: 'beverage_distribution', label: 'Beverage Distribution' },
  { value: 'craft_brewing', label: 'Craft Brewing' },
  { value: 'space_technology', label: 'Space Technology' },
  { value: 'drone_technology', label: 'Drone Technology' },
  { value: 'robotics', label: 'Robotics' },
  { value: 'biotechnology', label: 'Biotechnology' },
  { value: 'nanotechnology', label: 'Nanotechnology' },
  { value: 'water_management', label: 'Water Management' },
  { value: 'waste_management', label: 'Waste Management' },
  { value: 'recycling_services', label: 'Recycling Services' },
  { value: 'sustainable_packaging', label: 'Sustainable Packaging' },
  { value: 'green_technology', label: 'Green Technology' },
  { value: 'data_center_services', label: 'Data Center Services' },
  { value: 'cloud_infrastructure', label: 'Cloud Infrastructure' },
  { value: 'network_security', label: 'Network Security' },
  { value: 'it_consulting', label: 'IT Consulting' },
  { value: 'business_intelligence', label: 'Business Intelligence' },
  { value: 'digital_transformation', label: 'Digital Transformation' },
  { value: 'smart_manufacturing', label: 'Smart Manufacturing' },
  { value: 'aviation_training', label: 'Aviation Training' },
  { value: 'aircraft_maintenance', label: 'Aircraft Maintenance' },
  { value: 'marine_services', label: 'Marine Services' },
  { value: 'port_management', label: 'Port Management' },
  { value: 'shipping_services', label: 'Shipping Services' },
  { value: 'railway_services', label: 'Railway Services' },
  { value: 'taxi_services', label: 'Taxi Services' },
  { value: 'ride_hailing', label: 'Ride-Hailing' },
  { value: 'public_transportation', label: 'Public Transportation' },
  { value: 'logistics_automation', label: 'Logistics Automation' },
  { value: 'supply_chain_tech', label: 'Supply Chain Technology' },
  { value: 'warehouse_management', label: 'Warehouse Management' },
  { value: 'retail_banking', label: 'Retail Banking' },
  { value: 'wealth_management', label: 'Wealth Management' },
  { value: 'payment_solutions', label: 'Payment Solutions' },
  { value: 'cryptocurrency', label: 'Cryptocurrency' },
  { value: 'digital_banking', label: 'Digital Banking' },
  { value: 'financial_tech', label: 'Financial Technology' },
  { value: 'insurance_brokerage', label: 'Insurance Brokerage' },
  { value: 'real_estate_tech', label: 'Real Estate Technology' },
  { value: 'property_tech', label: 'Property Technology' },
  { value: 'construction_tech', label: 'Construction Technology' },
  { value: 'smart_construction', label: 'Smart Construction' },
  { value: 'building_information_modeling', label: 'Building Information Modeling (BIM)' },
  { value: 'urban_development', label: 'Urban Development' },
  { value: 'smart_cities', label: 'Smart Cities' },
  { value: 'infrastructure_tech', label: 'Infrastructure Technology' },
  { value: 'energy_consulting', label: 'Energy Consulting' },
  { value: 'oil_exploration', label: 'Oil Exploration' },
  { value: 'gas_exploration', label: 'Gas Exploration' },
  { value: 'renewable_materials', label: 'Renewable Materials' },
  { value: 'sustainable_construction', label: 'Sustainable Construction' },
  { value: 'environmental_consulting', label: 'Environmental Consulting' },
  { value: 'clean_energy', label: 'Clean Energy' },
  { value: 'geothermal_energy', label: 'Geothermal Energy' },
  { value: 'hydrogen_energy', label: 'Hydrogen Energy' },
  { value: 'solar_tech', label: 'Solar Technology' },
  { value: 'wind_tech', label: 'Wind Technology' },
  { value: 'energy_management', label: 'Energy Management' },
  { value: 'healthcare_tech', label: 'Healthcare Technology' },
  { value: 'telemedicine', label: 'Telemedicine' },
  { value: 'medical_imaging', label: 'Medical Imaging' },
  { value: 'pharmacy_services', label: 'Pharmacy Services' },
  { value: 'healthcare_consulting', label: 'Healthcare Consulting' },
  { value: 'biomedical_research', label: 'Biomedical Research' },
  { value: 'genetic_research', label: 'Genetic Research' },
  { value: 'hospital_management', label: 'Hospital Management' },
  { value: 'luxury_travel', label: 'Luxury Travel' },
  { value: 'travel_tech', label: 'Travel Technology' },
  { value: 'tourism_management', label: 'Tourism Management' },
  { value: 'event_planning', label: 'Event Planning' },
  { value: 'cruise_lines', label: 'Cruise Lines' },
  { value: 'aviation_services', label: 'Aviation Services' },
  { value: 'retail_technology', label: 'Retail Technology' },
  { value: 'ecommerce_platforms', label: 'E-Commerce Platforms' },
  { value: 'digital_retail', label: 'Digital Retail' },
  { value: 'omni_channel_retail', label: 'Omni-Channel Retail' },
  { value: 'fashion_design', label: 'Fashion Design' },
  { value: 'jewelry_design', label: 'Jewelry Design' },
  { value: 'cosmetics_manufacturing', label: 'Cosmetics Manufacturing' },
  { value: 'beauty_tech', label: 'Beauty Technology' },
  { value: 'food_tech', label: 'Food Technology' },
  { value: 'agri_tech', label: 'Agricultural Technology' },
  { value: 'fisheries', label: 'Fisheries' },
  { value: 'food_distribution', label: 'Food Distribution' },
  { value: 'beverage_manufacturing', label: 'Beverage Manufacturing' },
  { value: 'catering_tech', label: 'Catering Technology' },
  { value: 'restaurant_tech', label: 'Restaurant Technology' },
  { value: 'gaming_tech', label: 'Gaming Technology' },
  { value: 'esports', label: 'Esports' },
  { value: 'animation', label: 'Animation' },
  { value: 'digital_media', label: 'Digital Media' },
  { value: 'content_creation', label: 'Content Creation' },
  { value: 'video_production', label: 'Video Production' },
  { value: 'music_distribution', label: 'Music Distribution' },
  { value: 'entertainment_tech', label: 'Entertainment Technology' },
  { value: 'sports_tech', label: 'Sports Technology' },
  { value: 'fitness_services', label: 'Fitness Services' },
  { value: 'fitness_tech', label: 'Fitness Technology' },
  { value: 'wellness_services', label: 'Wellness Services' },
  { value: 'mental_health_tech', label: 'Mental Health Technology' },
  { value: 'nutrition_services', label: 'Nutrition Services' },
  { value: 'veterinary_services', label: 'Veterinary Services' },
  { value: 'pet_tech', label: 'Pet Technology' },
  { value: 'security_tech', label: 'Security Technology' },
  { value: 'defense_tech', label: 'Defense Technology' },
  { value: 'aerospace_tech', label: 'Aerospace Technology' },
  { value: 'automotive_tech', label: 'Automotive Technology' },
  { value: 'manufacturing_tech', label: 'Manufacturing Technology' },
  { value: 'semiconductor_design', label: 'Semiconductor Design' },
  { value: 'robotics_engineering', label: 'Robotics Engineering' },
  { value: '3d_printing', label: '3D Printing' },
  { value: 'industrial_design', label: 'Industrial Design' },
  { value: 'packaging_industry', label: 'Packaging Industry' },
  { value: 'sustainable_packaging', label: 'Sustainable Packaging' },
  { value: 'textile_design', label: 'Textile Design' },
  { value: 'furniture_design', label: 'Furniture Design' },
  { value: 'interior_design', label: 'Interior Design' },
  { value: 'landscape_architecture', label: 'Landscape Architecture' },
  { value: 'graphic_design', label: 'Graphic Design' },
  { value: 'animation_studios', label: 'Animation Studios' },
  { value: 'photography_services', label: 'Photography Services' },
  { value: 'art_galleries', label: 'Art Galleries' },
  { value: 'cultural_heritage', label: 'Cultural Heritage' },
  { value: 'museum_management', label: 'Museum Management' },
  { value: 'public_safety', label: 'Public Safety' },
  { value: 'emergency_services', label: 'Emergency Services' },
  { value: 'legal_services', label: 'Legal Services' },
  { value: 'legal_tech', label: 'Legal Technology' },
  { value: 'consulting_services', label: 'Consulting Services' },
  { value: 'business_consulting', label: 'Business Consulting' },
  { value: 'management_consulting', label: 'Management Consulting' },
  { value: 'hr_consulting', label: 'Human Resources Consulting' },
  { value: 'market_research', label: 'Market Research' },
  { value: 'data_management', label: 'Data Management' },
  { value: 'customer_support', label: 'Customer Support' },
  { value: 'call_center_services', label: 'Call Center Services' },
  { value: 'outsourcing_services', label: 'Outsourcing Services' },
  { value: 'nonprofit', label: 'Nonprofit' },
  { value: 'humanitarian_aid', label: 'Humanitarian Aid' },
  { value: 'government_services', label: 'Government Services' },
  { value: 'public_administration', label: 'Public Administration' },
  { value: 'smart_infrastructure', label: 'Smart Infrastructure' },
  { value: 'digital_government', label: 'Digital Government' },
  { value: 'urban_tech', label: 'Urban Technology' },
  { value: 'smart_transportation', label: 'Smart Transportation' },
  { value: 'energy_tech', label: 'Energy Technology' },
  { value: 'clean_tech', label: 'Clean Technology' },
  { value: 'environmental_tech', label: 'Environmental Technology' },
  { value: 'water_tech', label: 'Water Technology' },
  { value: 'waste_tech', label: 'Waste Technology' },
  { value: 'sustainable_tech', label: 'Sustainable Technology' },
  { value: 'green_building', label: 'Green Building' },
  { value: 'smart_energy', label: 'Smart Energy' },
  { value: 'digital_health', label: 'Digital Health' },
  { value: 'e_learning', label: 'E-Learning' },
  { value: 'online_training', label: 'Online Training' },
  { value: 'virtual_events', label: 'Virtual Events' },
  { value: 'digital_advertising', label: 'Digital Advertising' },
  { value: 'social_media_tech', label: 'Social Media Technology' },
  { value: 'content_marketing', label: 'Content Marketing' },
  { value: 'influencer_marketing', label: 'Influencer Marketing' },
  { value: 'online_pr', label: 'Online Public Relations' },
  { value: 'digital_publishing', label: 'Digital Publishing' },
  { value: 'ecommerce_logistics', label: 'E-Commerce Logistics' },
  { value: 'last_mile_delivery', label: 'Last-Mile Delivery' },
  { value: 'smart_logistics', label: 'Smart Logistics' },
  { value: 'digital_supply_chain', label: 'Digital Supply Chain' },
  { value: 'fleet_management', label: 'Fleet Management' },
  { value: 'aviation_tech', label: 'Aviation Technology' },
  { value: 'space_exploration', label: 'Space Exploration' },
  { value: 'drone_services', label: 'Drone Services' },
  { value: 'smart_mobility', label: 'Smart Mobility' },
  { value: 'shared_mobility', label: 'Shared Mobility' },
  { value: 'transportation_tech', label: 'Transportation Technology' },
  { value: 'digital_infrastructure', label: 'Digital Infrastructure' },
  { value: '5g_services', label: '5G Services' },
  { value: 'cloud_services', label: 'Cloud Services' },
  { value: 'ai_solutions', label: 'AI Solutions' },
  { value: 'blockchain_services', label: 'Blockchain Services' },
  { value: 'cybersecurity_solutions', label: 'Cybersecurity Solutions' },
  { value: 'data_science', label: 'Data Science' },
  { value: 'machine_learning', label: 'Machine Learning' },
  { value: 'big_data', label: 'Big Data' },
  { value: 'business_analytics', label: 'Business Analytics' },
  { value: 'smart_retail', label: 'Smart Retail' },
  { value: 'digital_payments', label: 'Digital Payments' },
  { value: 'fintech_solutions', label: 'Fintech Solutions' },
  { value: 'smart_healthcare', label: 'Smart Healthcare' },
  { value: 'telehealth', label: 'Telehealth' },
  { value: 'health_tech', label: 'Health Technology' },
  { value: 'smart_education', label: 'Smart Education' },
  { value: 'digital_tourism', label: 'Digital Tourism' },
  { value: 'smart_hospitality', label: 'Smart Hospitality' },
  { value: 'gaming_industry', label: 'Gaming Industry' },
  { value: 'esports_tech', label: 'Esports Technology' },
  { value: 'digital_entertainment', label: 'Digital Entertainment' },
  { value: 'smart_manufacturing', label: 'Smart Manufacturing' },
  { value: 'industrial_tech', label: 'Industrial Technology' },
  { value: 'construction_innovation', label: 'Construction Innovation' },
  { value: 'smart_real_estate', label: 'Smart Real Estate' },
  { value: 'proptech', label: 'Property Technology' },
  { value: 'digital_construction', label: 'Digital Construction' },
  { value: 'sustainable_real_estate', label: 'Sustainable Real Estate' },
  { value: 'smart_energy_solutions', label: 'Smart Energy Solutions' },
  { value: 'renewable_tech', label: 'Renewable Technology' },
  { value: 'green_infrastructure', label: 'Green Infrastructure' },
  { value: 'smart_grid', label: 'Smart Grid' },
  { value: 'energy_innovation', label: 'Energy Innovation' },
  { value: 'digital_energy', label: 'Digital Energy' },
  { value: 'sustainable_transport', label: 'Sustainable Transport' },
  { value: 'smart_vehicle_tech', label: 'Smart Vehicle Technology' },
  { value: 'autonomous_vehicles', label: 'Autonomous Vehicles' },
  { value: 'ev_charging', label: 'EV Charging Infrastructure' },
  { value: 'smart_aviation', label: 'Smart Aviation' },
  { value: 'digital_logistics', label: 'Digital Logistics' },
  { value: 'supply_chain_innovation', label: 'Supply Chain Innovation' },
  { value: 'smart_warehouse', label: 'Smart Warehouse' },
  { value: 'ecommerce_tech', label: 'E-Commerce Technology' },
  { value: 'digital_marketplace', label: 'Digital Marketplace' },
  { value: 'online_gaming', label: 'Online Gaming' },
  { value: 'digital_fashion', label: 'Digital Fashion' },
  { value: 'smart_farming', label: 'Smart Farming' },
  { value: 'precision_agriculture', label: 'Precision Agriculture' },
  { value: 'food_innovation', label: 'Food Innovation' },
  { value: 'sustainable_food', label: 'Sustainable Food' },
  { value: 'digital_healthcare', label: 'Digital Healthcare' },
  { value: 'smart_tourism', label: 'Smart Tourism' },
  { value: 'digital_hospitality', label: 'Digital Hospitality' },
  { value: 'smart_entertainment', label: 'Smart Entertainment' },
  { value: 'digital_sports', label: 'Digital Sports' },
  { value: 'esports_management', label: 'Esports Management' },
  { value: 'smart_security', label: 'Smart Security' },
  { value: 'digital_defense', label: 'Digital Defense' },
  { value: 'smart_aerospace', label: 'Smart Aerospace' },
  { value: 'digital_manufacturing', label: 'Digital Manufacturing' },
  { value: 'smart_supply_chain', label: 'Smart Supply Chain' },
  { value: 'digital_urban_planning', label: 'Digital Urban Planning' },
  { value: 'smart_real_estate_solutions', label: 'Smart Real Estate Solutions' },
  { value: 'digital_energy_solutions', label: 'Digital Energy Solutions' },
  { value: 'smart_health_solutions', label: 'Smart Health Solutions' },
  { value: 'digital_education_solutions', label: 'Digital Education Solutions' },
  { value: 'smart_retail_solutions', label: 'Smart Retail Solutions' },
  { value: 'digital_tourism_solutions', label: 'Digital Tourism Solutions' },
  { value: 'smart_hospitality_solutions', label: 'Smart Hospitality Solutions' },
  { value: 'digital_entertainment_solutions', label: 'Digital Entertainment Solutions' },
  { value: 'smart_finance_solutions', label: 'Smart Finance Solutions' },
  { value: 'digital_logistics_solutions', label: 'Digital Logistics Solutions' },
  { value: 'smart_manufacturing_solutions', label: 'Smart Manufacturing Solutions' },
  { value: 'digital_security_solutions', label: 'Digital Security Solutions' },
  { value: 'smart_energy_tech', label: 'Smart Energy Technology' },
  { value: 'digital_health_tech', label: 'Digital Health Technology' },
  { value: 'smart_education_tech', label: 'Smart Education Technology' },
  { value: 'digital_tourism_tech', label: 'Digital Tourism Technology' },
  { value: 'smart_hospitality_tech', label: 'Smart Hospitality Technology' },
  { value: 'digital_entertainment_tech', label: 'Digital Entertainment Technology' },
  { value: 'smart_finance_tech', label: 'Smart Finance Technology' },
  { value: 'digital_logistics_tech', label: 'Digital Logistics Technology' },
  { value: 'smart_manufacturing_tech', label: 'Smart Manufacturing Technology' },
  { value: 'digital_security_tech', label: 'Digital Security Technology' },
  { value: 'quantum_computing', label: 'Quantum Computing' },
  { value: 'edge_computing', label: 'Edge Computing' },
  { value: 'computer_vision', label: 'Computer Vision' },
  { value: 'natural_language_processing', label: 'Natural Language Processing' },
  { value: 'deep_learning', label: 'Deep Learning' },
  { value: 'generative_ai', label: 'Generative AI' },
  { value: 'ai_ethics', label: 'AI Ethics' },
  { value: 'ai_governance', label: 'AI Governance' },
  { value: 'predictive_analytics', label: 'Predictive Analytics' },
  { value: 'prescriptive_analytics', label: 'Prescriptive Analytics' },
  { value: 'ai_hardware', label: 'AI Hardware' },
  { value: 'neuromorphic_computing', label: 'Neuromorphic Computing' },
  { value: 'digital_twin_technology', label: 'Digital Twin Technology' },
  { value: 'extended_reality', label: 'Extended Reality (XR)' },
  { value: 'mixed_reality', label: 'Mixed Reality' },
  { value: 'spatial_computing', label: 'Spatial Computing' },
  { value: 'metaverse_development', label: 'Metaverse Development' },
  { value: 'virtual_collaboration', label: 'Virtual Collaboration' },
  { value: 'cloud_security', label: 'Cloud Security' },
  { value: 'devops_services', label: 'DevOps Services' },
  { value: 'site_reliability_engineering', label: 'Site Reliability Engineering (SRE)' },
  { value: 'platform_engineering', label: 'Platform Engineering' },
  { value: 'low_code_development', label: 'Low-Code Development' },
  { value: 'no_code_development', label: 'No-Code Development' },
  { value: 'api_development', label: 'API Development' },
  { value: 'microservices_architecture', label: 'Microservices Architecture' },
  { value: 'serverless_computing', label: 'Serverless Computing' },
  { value: 'containerization', label: 'Containerization' },
  { value: 'kubernetes_orchestration', label: 'Kubernetes Orchestration' },
  { value: 'cloud_native_development', label: 'Cloud-Native Development' },
  { value: 'enterprise_software', label: 'Enterprise Software' },
  { value: 'crm_software', label: 'CRM Software' },
  { value: 'erp_software', label: 'ERP Software' },
  { value: 'saaS_development', label: 'SaaS Development' },
  { value: 'paas_development', label: 'PaaS Development' },
  { value: 'iaas_providers', label: 'IaaS Providers' },
  { value: 'data_lake_management', label: 'Data Lake Management' },
  { value: 'data_warehouse_solutions', label: 'Data Warehouse Solutions' },
  { value: 'data_integration', label: 'Data Integration' },
  { value: 'data_governance', label: 'Data Governance' },
  { value: 'data_privacy_solutions', label: 'Data Privacy Solutions' },
  { value: 'cyber_threat_intelligence', label: 'Cyber Threat Intelligence' },
  { value: 'zero_trust_security', label: 'Zero Trust Security' },
  { value: 'endpoint_security', label: 'Endpoint Security' },
  { value: 'identity_management', label: 'Identity Management' },
  { value: 'access_control_systems', label: 'Access Control Systems' },
  { value: 'network_monitoring', label: 'Network Monitoring' },
  { value: 'it_automation', label: 'IT Automation' },
  { value: 'robotic_process_automation', label: 'Robotic Process Automation (RPA)' },
  { value: 'ai_automation', label: 'AI Automation' },
  { value: 'chatbot_development', label: 'Chatbot Development' },
  { value: 'voice_recognition_tech', label: 'Voice Recognition Technology' },
  { value: 'speech_to_text', label: 'Speech-to-Text Technology' },
  { value: 'text_to_speech', label: 'Text-to-Speech Technology' },
  { value: 'geospatial_analysis', label: 'Geospatial Analysis' },
  { value: 'location_based_services', label: 'Location-Based Services' },
  { value: 'blockchain_security', label: 'Blockchain Security' },
  { value: 'decentralized_finance', label: 'Decentralized Finance (DeFi)' },
  { value: 'smart_contract_development', label: 'Smart Contract Development' },
  { value: 'nft_platforms', label: 'NFT Platforms' },
  { value: 'web3_development', label: 'Web3 Development' },
  { value: 'crypto_wallet_development', label: 'Crypto Wallet Development' },
  { value: 'blockchain_consulting', label: 'Blockchain Consulting' },
  { value: 'iot_security', label: 'IoT Security' },
  { value: 'edge_ai', label: 'Edge AI' },
  { value: 'iot_platforms', label: 'IoT Platforms' },
  { value: 'smart_home_tech', label: 'Smart Home Technology' },
  { value: 'industrial_iot', label: 'Industrial IoT' },
  { value: 'wearable_technology', label: 'Wearable Technology' },
  { value: 'embedded_systems', label: 'Embedded Systems' },
  { value: 'firmware_development', label: 'Firmware Development' },
  { value: 'hardware_design', label: 'Hardware Design' },
  { value: 'chip_design', label: 'Chip Design' },
  { value: 'computer_networking_solutions', label: 'Computer Networking Solutions' },
  { value: 'software_testing_automation', label: 'Software Testing Automation' },
  { value: 'quality_assurance_it', label: 'Quality Assurance (IT)' },
  { value: 'ui_ux_design', label: 'UI/UX Design' },
  { value: 'user_experience_research', label: 'User Experience Research' },
  { value: 'frontend_development', label: 'Frontend Development' },
  { value: 'backend_development', label: 'Backend Development' },
  { value: 'full_stack_development', label: 'Full Stack Development' },
  { value: 'database_management', label: 'Database Management' },
  { value: 'big_data_engineering', label: 'Big Data Engineering' },
  { value: 'data_visualization', label: 'Data Visualization' },
  { value: 'business_process_automation', label: 'Business Process Automation' },
  { value: 'enterprise_mobility', label: 'Enterprise Mobility' },
  { value: 'mobile_payment_solutions', label: 'Mobile Payment Solutions' },
  { value: 'digital_wallet_development', label: 'Digital Wallet Development' },
  { value: 'cloud_migration_services', label: 'Cloud Migration Services' },
  { value: 'it_support_services', label: 'IT Support Services' },
  { value: 'managed_it_services', label: 'Managed IT Services' },
  { value: 'it_outsourcing', label: 'IT Outsourcing' },
  { value: 'cybersecurity_consulting', label: 'Cybersecurity Consulting' },
  { value: 'penetration_testing', label: 'Penetration Testing' },
  { value: 'vulnerability_assessment', label: 'Vulnerability Assessment' },
  { value: 'data_encryption', label: 'Data Encryption' },
  { value: 'ai_model_development', label: 'AI Model Development' },
  { value: 'ai_consulting', label: 'AI Consulting' },
  { value: 'machine_vision', label: 'Machine Vision' },
   { value: 'cultural_tourism', label: 'Cultural Tourism' },
  { value: 'heritage_preservation', label: 'Heritage Preservation' },
  { value: 'museum_exhibitions', label: 'Museum Exhibitions' },
  { value: 'art_restoration', label: 'Art Restoration' },
  { value: 'historical_tours', label: 'Historical Tours' },
  { value: 'cultural_festivals', label: 'Cultural Festivals' },
  { value: 'traditional_crafts', label: 'Traditional Crafts' },
  { value: 'calligraphy_services', label: 'Calligraphy Services' },
  { value: 'arabic_calligraphy', label: 'Arabic Calligraphy' },
  { value: 'islamic_art', label: 'Islamic Art' },
  { value: 'cultural_events', label: 'Cultural Events' },
  { value: 'folk_music', label: 'Folk Music' },
  { value: 'traditional_dance', label: 'Traditional Dance' },
  { value: 'cultural_workshops', label: 'Cultural Workshops' },
  { value: 'heritage_tourism', label: 'Heritage Tourism' },
  { value: 'archaeological_services', label: 'Archaeological Services' },
  { value: 'cultural_consulting', label: 'Cultural Consulting' },
  { value: 'art_exhibitions', label: 'Art Exhibitions' },
  { value: 'contemporary_art', label: 'Contemporary Art' },
  { value: 'sculpture_art', label: 'Sculpture Art' },
  { value: 'visual_arts', label: 'Visual Arts' },
  { value: 'art_curation', label: 'Art Curation' },
  { value: 'cultural_education', label: 'Cultural Education' },
  { value: 'traditional_fashion', label: 'Traditional Fashion' },
  { value: 'textile_arts', label: 'Textile Arts' },
  { value: 'handicraft_production', label: 'Handicraft Production' },
  { value: 'jewelry_crafting', label: 'Jewelry Crafting' },
  { value: 'ceramic_arts', label: 'Ceramic Arts' },
  { value: 'pottery_making', label: 'Pottery Making' },
  { value: 'cultural_media', label: 'Cultural Media' },
  { value: 'documentary_filmmaking', label: 'Documentary Filmmaking' },
  { value: 'cultural_journalism', label: 'Cultural Journalism' },
  { value: 'art_publishing', label: 'Art Publishing' },
  { value: 'literary_publishing', label: 'Literary Publishing' },
  { value: 'cultural_broadcasting', label: 'Cultural Broadcasting' },
  { value: 'traditional_storytelling', label: 'Traditional Storytelling' },
  { value: 'poetry_events', label: 'Poetry Events' },
  { value: 'literary_festivals', label: 'Literary Festivals' },
  { value: 'book_fairs', label: 'Book Fairs' },
  { value: 'cultural_marketing', label: 'Cultural Marketing' },
  { value: 'art_advisory', label: 'Art Advisory' },
  { value: 'cultural_diplomacy', label: 'Cultural Diplomacy' },
  { value: 'heritage_management', label: 'Heritage Management' },
  { value: 'cultural_research', label: 'Cultural Research' },
  { value: 'museum_technology', label: 'Museum Technology' },
  { value: 'virtual_museums', label: 'Virtual Museums' },
  { value: 'cultural_digitization', label: 'Cultural Digitization' },
  { value: 'digital_archives', label: 'Digital Archives' },
  { value: 'historical_reenactment', label: 'Historical Reenactment' },
  { value: 'cultural_performances', label: 'Cultural Performances' },
  { value: 'theater_production', label: 'Theater Production' },
  { value: 'opera_production', label: 'Opera Production' },
  { value: 'dance_companies', label: 'Dance Companies' },
  { value: 'music_festivals', label: 'Music Festivals' },
  { value: 'cultural_training', label: 'Cultural Training' },
  { value: 'art_education', label: 'Art Education' },
  { value: 'music_education', label: 'Music Education' },
  { value: 'dance_education', label: 'Dance Education' },
  { value: 'cultural_sponsorship', label: 'Cultural Sponsorship' },
  { value: 'art_funding', label: 'Art Funding' },
  { value: 'cultural_grants', label: 'Cultural Grants' },
  { value: 'public_art_installations', label: 'Public Art Installations' },
  { value: 'street_art', label: 'Street Art' },
  { value: 'cultural_photography', label: 'Cultural Photography' },
  { value: 'fashion_curation', label: 'Fashion Curation' },
  { value: 'cultural_brand_management', label: 'Cultural Brand Management' },
  { value: 'art_auctions', label: 'Art Auctions' },
  { value: 'cultural_tour_guides', label: 'Cultural Tour Guides' },
  { value: 'heritage_site_management', label: 'Heritage Site Management' },
  { value: 'cultural_event_planning', label: 'Cultural Event Planning' },
  { value: 'traditional_music_production', label: 'Traditional Music Production' },
  { value: 'cultural_content_creation', label: 'Cultural Content Creation' },
  { value: 'artisan_workshops', label: 'Artisan Workshops' },
  { value: 'cultural_influencer_marketing', label: 'Cultural Influencer Marketing' },
  { value: 'folklore_preservation', label: 'Folklore Preservation' },
  { value: 'cultural_documentation', label: 'Cultural Documentation' },
  { value: 'traditional_cuisine', label: 'Traditional Cuisine' },
  { value: 'culinary_arts', label: 'Culinary Arts' },
  { value: 'food_festivals', label: 'Food Festivals' },
  { value: 'cultural_culinary_tours', label: 'Cultural Culinary Tours' },
  { value: 'traditional_costume_design', label: 'Traditional Costume Design' },
  { value: 'cultural_fashion_shows', label: 'Cultural Fashion Shows' },
  { value: 'art_fair_management', label: 'Art Fair Management' },
  { value: 'cultural_exhibition_design', label: 'Cultural Exhibition Design' },
  { value: 'museum_curation', label: 'Museum Curation' },
  { value: 'cultural_heritage_tech', label: 'Cultural Heritage Technology' },
  { value: 'digital_art', label: 'Digital Art' },
  { value: 'multimedia_art', label: 'Multimedia Art' },
  { value: 'cultural_streaming', label: 'Cultural Streaming' },
  { value: 'virtual_cultural_events', label: 'Virtual Cultural Events' },
  { value: 'cultural_app_development', label: 'Cultural App Development' },
  { value: 'heritage_education', label: 'Heritage Education' },
  { value: 'cultural_translation_services', label: 'Cultural Translation Services' },
  { value: 'traditional_games', label: 'Traditional Games' },
  { value: 'cultural_gaming', label: 'Cultural Gaming' },
  { value: 'art_therapy', label: 'Art Therapy' },
  { value: 'cultural_community_engagement', label: 'Cultural Community Engagement' },
  { value: 'cultural_nonprofits', label: 'Cultural Nonprofits' },
  { value: 'traditional_performing_arts', label: 'Traditional Performing Arts' },
  { value: 'cultural_policy_development', label: 'Cultural Policy Development' }
];