export const locationOptions = [
  // UAE - Complete coverage
  { value: 'abu_dhabi_uae', label: 'Abu Dhabi, UAE' },
  { value: 'ajman_uae', label: 'Ajman, UAE' },
  { value: 'al_ain_uae', label: 'Al Ain, UAE' },
  { value: 'dubai_uae', label: 'Dubai, UAE' },
  { value: 'fujairah_uae', label: 'Fujairah, UAE' },
  { value: 'ras_al_khaimah_uae', label: 'Ras Al Khaimah, UAE' },
  { value: 'sharjah_uae', label: 'Sharjah, UAE' },
  { value: 'umm_al_quwain_uae', label: 'Umm Al Quwain, UAE' },

  // Saudi Arabia - Major cities and regions
  { value: 'riyadh_saudi_arabia', label: 'Riyadh, Saudi Arabia' },
  { value: 'jeddah_saudi_arabia', label: 'Jeddah, Saudi Arabia' },
  { value: 'mecca_saudi_arabia', label: 'Mecca, Saudi Arabia' },
  { value: 'medina_saudi_arabia', label: 'Medina, Saudi Arabia' },
  { value: 'dammam_saudi_arabia', label: 'Dammam, Saudi Arabia' },
  { value: 'khobar_saudi_arabia', label: 'Khobar, Saudi Arabia' },
  { value: 'dhahran_saudi_arabia', label: 'Dhahran, Saudi Arabia' },
  { value: 'taif_saudi_arabia', label: 'Taif, Saudi Arabia' },
  { value: 'tabuk_saudi_arabia', label: 'Tabuk, Saudi Arabia' },
  { value: 'abha_saudi_arabia', label: 'Abha, Saudi Arabia' },
  { value: 'hail_saudi_arabia', label: 'Hail, Saudi Arabia' },
  { value: 'al_jubail_saudi_arabia', label: 'Al Jubail, Saudi Arabia' },
  { value: 'yanbu_saudi_arabia', label: 'Yanbu, Saudi Arabia' },
  { value: 'khamis_mushait_saudi_arabia', label: 'Khamis Mushait, Saudi Arabia' },
  { value: 'najran_saudi_arabia', label: 'Najran, Saudi Arabia' },
  { value: 'qatif_saudi_arabia', label: 'Qatif, Saudi Arabia' },

  // Qatar - Complete coverage
  { value: 'doha_qatar', label: 'Doha, Qatar' },
  { value: 'al_rayyan_qatar', label: 'Al Rayyan, Qatar' },
  { value: 'al_wakrah_qatar', label: 'Al Wakrah, Qatar' },
  { value: 'umm_salal_qatar', label: 'Umm Salal, Qatar' },
  { value: 'al_khor_qatar', label: 'Al Khor, Qatar' },
  { value: 'dukhan_qatar', label: 'Dukhan, Qatar' },
  { value: 'lusail_qatar', label: 'Lusail, Qatar' },

  // Kuwait - Complete coverage
  { value: 'kuwait_city_kuwait', label: 'Kuwait City, Kuwait' },
  { value: 'hawally_kuwait', label: 'Hawally, Kuwait' },
  { value: 'salmiya_kuwait', label: 'Salmiya, Kuwait' },
  { value: 'ahmadi_kuwait', label: 'Ahmadi, Kuwait' },
  { value: 'jahra_kuwait', label: 'Jahra, Kuwait' },
  { value: 'farwaniya_kuwait', label: 'Farwaniya, Kuwait' },
  { value: 'mubarak_al_kabeer_kuwait', label: 'Mubarak Al Kabeer, Kuwait' },

  // Bahrain - Complete coverage
  { value: 'manama_bahrain', label: 'Manama, Bahrain' },
  { value: 'muharraq_bahrain', label: 'Muharraq, Bahrain' },
  { value: 'riffa_bahrain', label: 'Riffa, Bahrain' },
  { value: 'hamad_town_bahrain', label: 'Hamad Town, Bahrain' },
  { value: 'isa_town_bahrain', label: 'Isa Town, Bahrain' },
  { value: 'sitra_bahrain', label: 'Sitra, Bahrain' },

  // Oman - Complete coverage
  { value: 'muscat_oman', label: 'Muscat, Oman' },
  { value: 'salalah_oman', label: 'Salalah, Oman' },
  { value: 'sohar_oman', label: 'Sohar, Oman' },
  { value: 'nizwa_oman', label: 'Nizwa, Oman' },
  { value: 'sur_oman', label: 'Sur, Oman' },
  { value: 'ibri_oman', label: 'Ibri, Oman' },
  { value: 'rustaq_oman', label: 'Rustaq, Oman' },
  { value: 'barka_oman', label: 'Barka, Oman' },
  { value: 'seeb_oman', label: 'Seeb, Oman' },

  // Jordan - Complete coverage
  { value: 'amman_jordan', label: 'Amman, Jordan' },
  { value: 'zarqa_jordan', label: 'Zarqa, Jordan' },
  { value: 'irbid_jordan', label: 'Irbid, Jordan' },
  { value: 'aqaba_jordan', label: 'Aqaba, Jordan' },
  { value: 'salt_jordan', label: 'Salt, Jordan' },
  { value: 'madaba_jordan', label: 'Madaba, Jordan' },
  { value: 'jerash_jordan', label: 'Jerash, Jordan' },
  { value: 'ajloun_jordan', label: 'Ajloun, Jordan' },
  { value: 'karak_jordan', label: 'Karak, Jordan' },
  { value: 'maan_jordan', label: 'Maan, Jordan' },

  // Lebanon - Complete coverage
  { value: 'beirut_lebanon', label: 'Beirut, Lebanon' },
  { value: 'tripoli_lebanon', label: 'Tripoli, Lebanon' },
  { value: 'sidon_lebanon', label: 'Sidon, Lebanon' },
  { value: 'tyre_lebanon', label: 'Tyre, Lebanon' },
  { value: 'baalbek_lebanon', label: 'Baalbek, Lebanon' },
  { value: 'jounieh_lebanon', label: 'Jounieh, Lebanon' },
  { value: 'zahle_lebanon', label: 'Zahle, Lebanon' },
  { value: 'nabatieh_lebanon', label: 'Nabatieh, Lebanon' },

  // Iraq - Major cities
  { value: 'baghdad_iraq', label: 'Baghdad, Iraq' },
  { value: 'basra_iraq', label: 'Basra, Iraq' },
  { value: 'erbil_iraq', label: 'Erbil, Iraq' },
  { value: 'mosul_iraq', label: 'Mosul, Iraq' },
  { value: 'najaf_iraq', label: 'Najaf, Iraq' },
  { value: 'karbala_iraq', label: 'Karbala, Iraq' },
  { value: 'sulaymaniyah_iraq', label: 'Sulaymaniyah, Iraq' },
  { value: 'kirkuk_iraq', label: 'Kirkuk, Iraq' },
  { value: 'dohuk_iraq', label: 'Dohuk, Iraq' },
  { value: 'hillah_iraq', label: 'Hillah, Iraq' },

  // Iran - Major cities
  { value: 'tehran_iran', label: 'Tehran, Iran' },
  { value: 'mashhad_iran', label: 'Mashhad, Iran' },
  { value: 'isfahan_iran', label: 'Isfahan, Iran' },
  { value: 'tabriz_iran', label: 'Tabriz, Iran' },
  { value: 'shiraz_iran', label: 'Shiraz, Iran' },
  { value: 'ahvaz_iran', label: 'Ahvaz, Iran' },
  { value: 'qom_iran', label: 'Qom, Iran' },
  { value: 'kermanshah_iran', label: 'Kermanshah, Iran' },
  { value: 'urmia_iran', label: 'Urmia, Iran' },
  { value: 'rasht_iran', label: 'Rasht, Iran' },
  { value: 'zahedan_iran', label: 'Zahedan, Iran' },
  { value: 'kerman_iran', label: 'Kerman, Iran' },
  { value: 'yazd_iran', label: 'Yazd, Iran' },
  { value: 'ardabil_iran', label: 'Ardabil, Iran' },
  { value: 'bandar_abbas_iran', label: 'Bandar Abbas, Iran' },

  // Yemen - Major cities
  { value: 'sana_yemen', label: "Sana'a, Yemen" },
  { value: 'aden_yemen', label: 'Aden, Yemen' },
  { value: 'taiz_yemen', label: 'Taiz, Yemen' },
  { value: 'hodeidah_yemen', label: 'Hodeidah, Yemen' },
  { value: 'ibb_yemen', label: 'Ibb, Yemen' },
  { value: 'mukalla_yemen', label: 'Mukalla, Yemen' },
  { value: 'dhamar_yemen', label: 'Dhamar, Yemen' },

  // Syria - Major cities
  { value: 'damascus_syria', label: 'Damascus, Syria' },
  { value: 'aleppo_syria', label: 'Aleppo, Syria' },
  { value: 'homs_syria', label: 'Homs, Syria' },
  { value: 'latakia_syria', label: 'Latakia, Syria' },
  { value: 'hama_syria', label: 'Hama, Syria' },
  { value: 'deir_ez_zor_syria', label: 'Deir ez-Zor, Syria' },
  { value: 'raqqa_syria', label: 'Raqqa, Syria' },
  { value: 'daraa_syria', label: 'Daraa, Syria' },
  { value: 'tartus_syria', label: 'Tartus, Syria' },

  // Palestine - Major cities
  { value: 'gaza_palestine', label: 'Gaza, Palestine' },
  { value: 'ramallah_palestine', label: 'Ramallah, Palestine' },
  { value: 'hebron_palestine', label: 'Hebron, Palestine' },
  { value: 'nablus_palestine', label: 'Nablus, Palestine' },
  { value: 'bethlehem_palestine', label: 'Bethlehem, Palestine' },
  { value: 'jenin_palestine', label: 'Jenin, Palestine' },
  { value: 'tulkarm_palestine', label: 'Tulkarm, Palestine' },

  // Israel - Major cities
  { value: 'jerusalem_israel', label: 'Jerusalem, Israel' },
  { value: 'tel_aviv_israel', label: 'Tel Aviv, Israel' },
  { value: 'haifa_israel', label: 'Haifa, Israel' },
  { value: 'rishon_lezion_israel', label: 'Rishon LeZion, Israel' },
  { value: 'petah_tikva_israel', label: 'Petah Tikva, Israel' },
  { value: 'ashdod_israel', label: 'Ashdod, Israel' },
  { value: 'netanya_israel', label: 'Netanya, Israel' },
  { value: 'beersheba_israel', label: 'Beersheba, Israel' },

  // Turkey - Major cities (part of Middle East)
  { value: 'ankara_turkey', label: 'Ankara, Turkey' },
  { value: 'istanbul_turkey', label: 'Istanbul, Turkey' },
  { value: 'izmir_turkey', label: 'Izmir, Turkey' },
  { value: 'bursa_turkey', label: 'Bursa, Turkey' },
  { value: 'antalya_turkey', label: 'Antalya, Turkey' },
  { value: 'gaziantep_turkey', label: 'Gaziantep, Turkey' },
  { value: 'konya_turkey', label: 'Konya, Turkey' },
  { value: 'adana_turkey', label: 'Adana, Turkey' },

  // Cyprus
  { value: 'nicosia_cyprus', label: 'Nicosia, Cyprus' },
  { value: 'limassol_cyprus', label: 'Limassol, Cyprus' },
  { value: 'larnaca_cyprus', label: 'Larnaca, Cyprus' },
  { value: 'paphos_cyprus', label: 'Paphos, Cyprus' },

  // Existing Asian locations (keeping for reference)
  { value: 'addu_city_maldives', label: 'Addu City, Maldives' },
  { value: 'ahmedabad_india', label: 'Ahmedabad, India' },
  { value: 'bandung_indonesia', label: 'Bandung, Indonesia' },
  { value: 'bangalore_india', label: 'Bangalore, India' },
  { value: 'bangkok_thailand', label: 'Bangkok, Thailand' },
  { value: 'beijing_china', label: 'Beijing, China' },
  { value: 'biratnagar_nepal', label: 'Biratnagar, Nepal' },
  { value: 'busan_south_korea', label: 'Busan, South Korea' },
  { value: 'can_tho_vietnam', label: 'Can Tho, Vietnam' },
  { value: 'cebu_philippines', label: 'Cebu, Philippines' },
  { value: 'chandigarh_india', label: 'Chandigarh, India' },
  { value: 'chengdu_china', label: 'Chengdu, China' },
  { value: 'chennai_india', label: 'Chennai, India' },
  { value: 'chiang_mai_thailand', label: 'Chiang Mai, Thailand' },
  { value: 'chittagong_bangladesh', label: 'Chittagong, Bangladesh' },
  { value: 'colombo_sri_lanka', label: 'Colombo, Sri Lanka' },
  { value: 'da_nang_vietnam', label: 'Da Nang, Vietnam' },
  { value: 'dar_es_salaam_tanzania', label: 'Dar es Salaam, Tanzania' },
  { value: 'davao_philippines', label: 'Davao, Philippines' },
  { value: 'delhi_india', label: 'Delhi, India' },
  { value: 'faisalabad_pakistan', label: 'Faisalabad, Pakistan' },
  { value: 'fukuoka_japan', label: 'Fukuoka, Japan' },
  { value: 'galle_sri_lanka', label: 'Galle, Sri Lanka' },
  { value: 'george_town_malaysia', label: 'George Town, Malaysia' },
  { value: 'guangzhou_china', label: 'Guangzhou, China' },
  { value: 'ho_chi_minh_city_vietnam', label: 'Ho Chi Minh City, Vietnam' },
  { value: 'hong_kong_hong_kong', label: 'Hong Kong, Hong Kong' },
  { value: 'hyderabad_india', label: 'Hyderabad, India' },
  { value: 'incheon_south_korea', label: 'Incheon, South Korea' },
  { value: 'ipoh_malaysia', label: 'Ipoh, Malaysia' },
  { value: 'islamabad_pakistan', label: 'Islamabad, Pakistan' },
  { value: 'jaipur_india', label: 'Jaipur, India' },
  { value: 'jakarta_indonesia', label: 'Jakarta, Indonesia' },
  { value: 'johor_bahru_malaysia', label: 'Johor Bahru, Malaysia' },
  { value: 'kandy_sri_lanka', label: 'Kandy, Sri Lanka' },
  { value: 'karachi_pakistan', label: 'Karachi, Pakistan' },
  { value: 'kathmandu_nepal', label: 'Kathmandu, Nepal' },
  { value: 'khulna_bangladesh', label: 'Khulna, Bangladesh' },
  { value: 'kolkata_india', label: 'Kolkata, India' },
  { value: 'kuala_lumpur_malaysia', label: 'Kuala Lumpur, Malaysia' },
  { value: 'lahore_pakistan', label: 'Lahore, Pakistan' },
  { value: 'lalitpur_nepal', label: 'Lalitpur, Nepal' },
  { value: 'male_maldives', label: 'Malé, Maldives' },
  { value: 'manila_philippines', label: 'Manila, Philippines' },
  { value: 'medan_indonesia', label: 'Medan, Indonesia' },
  { value: 'mumbai_india', label: 'Mumbai, India' },
  { value: 'nagoya_japan', label: 'Nagoya, Japan' },
  { value: 'osaka_japan', label: 'Osaka, Japan' },
  { value: 'paris_france', label: 'Paris, France' }, // example
  { value: 'penang_malaysia', label: 'Penang, Malaysia' },
  { value: 'peshawar_pakistan', label: 'Peshawar, Pakistan' },
  { value: 'phuket_thailand', label: 'Phuket, Thailand' },
  { value: 'pokhara_nepal', label: 'Pokhara, Nepal' },
  { value: 'pune_india', label: 'Pune, India' },
  { value: 'quetta_pakistan', label: 'Quetta, Pakistan' },
  { value: 'rajshahi_bangladesh', label: 'Rajshahi, Bangladesh' },
  { value: 'rawalpindi_pakistan', label: 'Rawalpindi, Pakistan' },
  { value: 'seoul_south_korea', label: 'Seoul, South Korea' },
  { value: 'shanghai_china', label: 'Shanghai, China' },
  { value: 'shenzhen_china', label: 'Shenzhen, China' },
  { value: 'sialkot_pakistan', label: 'Sialkot, Pakistan' },
  { value: 'singapore_singapore', label: 'Singapore' },
  { value: 'surat_india', label: 'Surat, India' },
  { value: 'taipei_taiwan', label: 'Taipei, Taiwan' },
  { value: 'thimphu_bhutan', label: 'Thimphu, Bhutan' },
  { value: 'tokyo_japan', label: 'Tokyo, Japan' },
  { value: 'wuhan_china', label: 'Wuhan, China' }
];