export const locationOptions = [
  // UAE - Complete coverage
  { value: 'abu_dhabi_uae', label: 'Abu Dhabi, UAE' },
  { value: 'ajman_uae', label: 'Ajman, UAE' },
  { value: 'al_ain_uae', label: 'Al Ain, UAE' },
  { value: 'dubai_uae', label: 'Dubai, UAE' },
  { value: 'fujairah_uae', label: 'Fujairah, UAE' },
  { value: 'ras_al_khaimah_uae', label: 'Ras Al Khaimah, UAE' },
  { value: 'sharjah_uae', label: 'Sharjah, UAE' },
  { value: 'umm_al_quwain_uae', label: 'Umm Al Quwain, UAE' },

  // Saudi Arabia - Major cities and regions
  { value: 'riyadh_saudi_arabia', label: 'Riyadh, Saudi Arabia' },
  { value: 'jeddah_saudi_arabia', label: 'Jeddah, Saudi Arabia' },
  { value: 'mecca_saudi_arabia', label: 'Mecca, Saudi Arabia' },
  { value: 'medina_saudi_arabia', label: 'Medina, Saudi Arabia' },
  { value: 'dammam_saudi_arabia', label: 'Dammam, Saudi Arabia' },
  { value: 'khobar_saudi_arabia', label: 'Khobar, Saudi Arabia' },
  { value: 'dhahran_saudi_arabia', label: 'Dhahran, Saudi Arabia' },
  { value: 'taif_saudi_arabia', label: 'Taif, Saudi Arabia' },
  { value: 'tabuk_saudi_arabia', label: 'Tabuk, Saudi Arabia' },
  { value: 'abha_saudi_arabia', label: 'Abha, Saudi Arabia' },
  { value: 'hail_saudi_arabia', label: 'Hail, Saudi Arabia' },
  { value: 'al_jubail_saudi_arabia', label: 'Al Jubail, Saudi Arabia' },
  { value: 'yanbu_saudi_arabia', label: 'Yanbu, Saudi Arabia' },
  { value: 'khamis_mushait_saudi_arabia', label: 'Khamis Mushait, Saudi Arabia' },
  { value: 'najran_saudi_arabia', label: 'Najran, Saudi Arabia' },
  { value: 'qatif_saudi_arabia', label: 'Qatif, Saudi Arabia' },

  // Qatar - Complete coverage
  { value: 'doha_qatar', label: 'Doha, Qatar' },
  { value: 'al_rayyan_qatar', label: 'Al Rayyan, Qatar' },
  { value: 'al_wakrah_qatar', label: 'Al Wakrah, Qatar' },
  { value: 'umm_salal_qatar', label: 'Umm Salal, Qatar' },
  { value: 'al_khor_qatar', label: 'Al Khor, Qatar' },
  { value: 'dukhan_qatar', label: 'Dukhan, Qatar' },
  { value: 'lusail_qatar', label: 'Lusail, Qatar' },

  // Kuwait - Complete coverage
  { value: 'kuwait_city_kuwait', label: 'Kuwait City, Kuwait' },
  { value: 'hawally_kuwait', label: 'Hawally, Kuwait' },
  { value: 'salmiya_kuwait', label: 'Salmiya, Kuwait' },
  { value: 'ahmadi_kuwait', label: 'Ahmadi, Kuwait' },
  { value: 'jahra_kuwait', label: 'Jahra, Kuwait' },
  { value: 'farwaniya_kuwait', label: 'Farwaniya, Kuwait' },
  { value: 'mubarak_al_kabeer_kuwait', label: 'Mubarak Al Kabeer, Kuwait' },

  // Bahrain - Complete coverage
  { value: 'manama_bahrain', label: 'Manama, Bahrain' },
  { value: 'muharraq_bahrain', label: 'Muharraq, Bahrain' },
  { value: 'riffa_bahrain', label: 'Riffa, Bahrain' },
  { value: 'hamad_town_bahrain', label: 'Hamad Town, Bahrain' },
  { value: 'isa_town_bahrain', label: 'Isa Town, Bahrain' },
  { value: 'sitra_bahrain', label: 'Sitra, Bahrain' },

  // Oman - Complete coverage
  { value: 'muscat_oman', label: 'Muscat, Oman' },
  { value: 'salalah_oman', label: 'Salalah, Oman' },
  { value: 'sohar_oman', label: 'Sohar, Oman' },
  { value: 'nizwa_oman', label: 'Nizwa, Oman' },
  { value: 'sur_oman', label: 'Sur, Oman' },
  { value: 'ibri_oman', label: 'Ibri, Oman' },
  { value: 'rustaq_oman', label: 'Rustaq, Oman' },
  { value: 'barka_oman', label: 'Barka, Oman' },
  { value: 'seeb_oman', label: 'Seeb, Oman' },

  // Jordan - Complete coverage
  { value: 'amman_jordan', label: 'Amman, Jordan' },
  { value: 'zarqa_jordan', label: 'Zarqa, Jordan' },
  { value: 'irbid_jordan', label: 'Irbid, Jordan' },
  { value: 'aqaba_jordan', label: 'Aqaba, Jordan' },
  { value: 'salt_jordan', label: 'Salt, Jordan' },
  { value: 'madaba_jordan', label: 'Madaba, Jordan' },
  { value: 'jerash_jordan', label: 'Jerash, Jordan' },
  { value: 'ajloun_jordan', label: 'Ajloun, Jordan' },
  { value: 'karak_jordan', label: 'Karak, Jordan' },
  { value: 'maan_jordan', label: 'Maan, Jordan' },

  // Lebanon - Complete coverage
  { value: 'beirut_lebanon', label: 'Beirut, Lebanon' },
  { value: 'tripoli_lebanon', label: 'Tripoli, Lebanon' },
  { value: 'sidon_lebanon', label: 'Sidon, Lebanon' },
  { value: 'tyre_lebanon', label: 'Tyre, Lebanon' },
  { value: 'baalbek_lebanon', label: 'Baalbek, Lebanon' },
  { value: 'jounieh_lebanon', label: 'Jounieh, Lebanon' },
  { value: 'zahle_lebanon', label: 'Zahle, Lebanon' },
  { value: 'nabatieh_lebanon', label: 'Nabatieh, Lebanon' },

  // Iraq - Major cities
  { value: 'baghdad_iraq', label: 'Baghdad, Iraq' },
  { value: 'basra_iraq', label: 'Basra, Iraq' },
  { value: 'erbil_iraq', label: 'Erbil, Iraq' },
  { value: 'mosul_iraq', label: 'Mosul, Iraq' },
  { value: 'najaf_iraq', label: 'Najaf, Iraq' },
  { value: 'karbala_iraq', label: 'Karbala, Iraq' },
  { value: 'sulaymaniyah_iraq', label: 'Sulaymaniyah, Iraq' },
  { value: 'kirkuk_iraq', label: 'Kirkuk, Iraq' },
  { value: 'dohuk_iraq', label: 'Dohuk, Iraq' },
  { value: 'hillah_iraq', label: 'Hillah, Iraq' },

  // Iran - Major cities
  { value: 'tehran_iran', label: 'Tehran, Iran' },
  { value: 'mashhad_iran', label: 'Mashhad, Iran' },
  { value: 'isfahan_iran', label: 'Isfahan, Iran' },
  { value: 'tabriz_iran', label: 'Tabriz, Iran' },
  { value: 'shiraz_iran', label: 'Shiraz, Iran' },
  { value: 'ahvaz_iran', label: 'Ahvaz, Iran' },
  { value: 'qom_iran', label: 'Qom, Iran' },
  { value: 'kermanshah_iran', label: 'Kermanshah, Iran' },
  { value: 'urmia_iran', label: 'Urmia, Iran' },
  { value: 'rasht_iran', label: 'Rasht, Iran' },
  { value: 'zahedan_iran', label: 'Zahedan, Iran' },
  { value: 'kerman_iran', label: 'Kerman, Iran' },
  { value: 'yazd_iran', label: 'Yazd, Iran' },
  { value: 'ardabil_iran', label: 'Ardabil, Iran' },
  { value: 'bandar_abbas_iran', label: 'Bandar Abbas, Iran' },

  // Yemen - Major cities
  { value: 'sana_yemen', label: "Sana'a, Yemen" },
  { value: 'aden_yemen', label: 'Aden, Yemen' },
  { value: 'taiz_yemen', label: 'Taiz, Yemen' },
  { value: 'hodeidah_yemen', label: 'Hodeidah, Yemen' },
  { value: 'ibb_yemen', label: 'Ibb, Yemen' },
  { value: 'mukalla_yemen', label: 'Mukalla, Yemen' },
  { value: 'dhamar_yemen', label: 'Dhamar, Yemen' },

  // Syria - Major cities
  { value: 'damascus_syria', label: 'Damascus, Syria' },
  { value: 'aleppo_syria', label: 'Aleppo, Syria' },
  { value: 'homs_syria', label: 'Homs, Syria' },
  { value: 'latakia_syria', label: 'Latakia, Syria' },
  { value: 'hama_syria', label: 'Hama, Syria' },
  { value: 'deir_ez_zor_syria', label: 'Deir ez-Zor, Syria' },
  { value: 'raqqa_syria', label: 'Raqqa, Syria' },
  { value: 'daraa_syria', label: 'Daraa, Syria' },
  { value: 'tartus_syria', label: 'Tartus, Syria' },

  // Palestine - Major cities
  { value: 'gaza_palestine', label: 'Gaza, Palestine' },
  { value: 'ramallah_palestine', label: 'Ramallah, Palestine' },
  { value: 'hebron_palestine', label: 'Hebron, Palestine' },
  { value: 'nablus_palestine', label: 'Nablus, Palestine' },
  { value: 'bethlehem_palestine', label: 'Bethlehem, Palestine' },
  { value: 'jenin_palestine', label: 'Jenin, Palestine' },
  { value: 'tulkarm_palestine', label: 'Tulkarm, Palestine' },

  // Israel - Major cities
  { value: 'jerusalem_israel', label: 'Jerusalem, Israel' },
  { value: 'tel_aviv_israel', label: 'Tel Aviv, Israel' },
  { value: 'haifa_israel', label: 'Haifa, Israel' },
  { value: 'rishon_lezion_israel', label: 'Rishon LeZion, Israel' },
  { value: 'petah_tikva_israel', label: 'Petah Tikva, Israel' },
  { value: 'ashdod_israel', label: 'Ashdod, Israel' },
  { value: 'netanya_israel', label: 'Netanya, Israel' },
  { value: 'beersheba_israel', label: 'Beersheba, Israel' },

  // Turkey - Major cities
  { value: 'ankara_turkey', label: 'Ankara, Turkey' },
  { value: 'istanbul_turkey', label: 'Istanbul, Turkey' },
  { value: 'izmir_turkey', label: 'Izmir, Turkey' },
  { value: 'bursa_turkey', label: 'Bursa, Turkey' },
  { value: 'antalya_turkey', label: 'Antalya, Turkey' },
  { value: 'gaziantep_turkey', label: 'Gaziantep, Turkey' },
  { value: 'konya_turkey', label: 'Konya, Turkey' },
  { value: 'adana_turkey', label: 'Adana, Turkey' },

  // Cyprus
  { value: 'nicosia_cyprus', label: 'Nicosia, Cyprus' },
  { value: 'limassol_cyprus', label: 'Limassol, Cyprus' },
  { value: 'larnaca_cyprus', label: 'Larnaca, Cyprus' },
  { value: 'paphos_cyprus', label: 'Paphos, Cyprus' },

  // Asian locations
  { value: 'addu_city_maldives', label: 'Addu City, Maldives' },
  { value: 'ahmedabad_india', label: 'Ahmedabad, India' },
  { value: 'bandung_indonesia', label: 'Bandung, Indonesia' },
  { value: 'bangalore_india', label: 'Bangalore, India' },
  { value: 'bangkok_thailand', label: 'Bangkok, Thailand' },
  { value: 'beijing_china', label: 'Beijing, China' },
  { value: 'biratnagar_nepal', label: 'Biratnagar, Nepal' },
  { value: 'busan_south_korea', label: 'Busan, South Korea' },
  { value: 'can_tho_vietnam', label: 'Can Tho, Vietnam' },
  { value: 'cebu_philippines', label: 'Cebu, Philippines' },
  { value: 'chandigarh_india', label: 'Chandigarh, India' },
  { value: 'chengdu_china', label: 'Chengdu, China' },
  { value: 'chennai_india', label: 'Chennai, India' },
  { value: 'chiang_mai_thailand', label: 'Chiang Mai, Thailand' },
  { value: 'chittagong_bangladesh', label: 'Chittagong, Bangladesh' },
  { value: 'colombo_sri_lanka', label: 'Colombo, Sri Lanka' },
  { value: 'da_nang_vietnam', label: 'Da Nang, Vietnam' },
  { value: 'davao_philippines', label: 'Davao, Philippines' },
  { value: 'delhi_india', label: 'Delhi, India' },
  { value: 'faisalabad_pakistan', label: 'Faisalabad, Pakistan' },
  { value: 'fukuoka_japan', label: 'Fukuoka, Japan' },
  { value: 'galle_sri_lanka', label: 'Galle, Sri Lanka' },
  { value: 'george_town_malaysia', label: 'George Town, Malaysia' },
  { value: 'guangzhou_china', label: 'Guangzhou, China' },
  { value: 'ho_chi_minh_city_vietnam', label: 'Ho Chi Minh City, Vietnam' },
  { value: 'hong_kong_hong_kong', label: 'Hong Kong, Hong Kong' },
  { value: 'hyderabad_india', label: 'Hyderabad, India' },
  { value: 'incheon_south_korea', label: 'Incheon, South Korea' },
  { value: 'ipoh_malaysia', label: 'Ipoh, Malaysia' },
  { value: 'islamabad_pakistan', label: 'Islamabad, Pakistan' },
  { value: 'jaipur_india', label: 'Jaipur, India' },
  { value: 'jakarta_indonesia', label: 'Jakarta, Indonesia' },
  { value: 'johor_bahru_malaysia', label: 'Johor Bahru, Malaysia' },
  { value: 'kandy_sri_lanka', label: 'Kandy, Sri Lanka' },
  { value: 'karachi_pakistan', label: 'Karachi, Pakistan' },
  { value: 'kathmandu_nepal', label: 'Kathmandu, Nepal' },
  { value: 'khulna_bangladesh', label: 'Khulna, Bangladesh' },
  { value: 'kolkata_india', label: 'Kolkata, India' },
  { value: 'kuala_lumpur_malaysia', label: 'Kuala Lumpur, Malaysia' },
  { value: 'lahore_pakistan', label: 'Lahore, Pakistan' },
  { value: 'lalitpur_nepal', label: 'Lalitpur, Nepal' },
  { value: 'male_maldives', label: 'Malé, Maldives' },
  { value: 'manila_philippines', label: 'Manila, Philippines' },
  { value: 'medan_indonesia', label: 'Medan, Indonesia' },
  { value: 'mumbai_india', label: 'Mumbai, India' },
  { value: 'nagoya_japan', label: 'Nagoya, Japan' },
  { value: 'osaka_japan', label: 'Osaka, Japan' },
  { value: 'penang_malaysia', label: 'Penang, Malaysia' },
  { value: 'peshawar_pakistan', label: 'Peshawar, Pakistan' },
  { value: 'phuket_thailand', label: 'Phuket, Thailand' },
  { value: 'pokhara_nepal', label: 'Pokhara, Nepal' },
  { value: 'pune_india', label: 'Pune, India' },
  { value: 'quetta_pakistan', label: 'Quetta, Pakistan' },
  { value: 'rajshahi_bangladesh', label: 'Rajshahi, Bangladesh' },
  { value: 'rawalpindi_pakistan', label: 'Rawalpindi, Pakistan' },
  { value: 'seoul_south_korea', label: 'Seoul, South Korea' },
  { value: 'shanghai_china', label: 'Shanghai, China' },
  { value: 'shenzhen_china', label: 'Shenzhen, China' },
  { value: 'sialkot_pakistan', label: 'Sialkot, Pakistan' },
  { value: 'singapore_singapore', label: 'Singapore' },
  { value: 'surat_india', label: 'Surat, India' },
  { value: 'taipei_taiwan', label: 'Taipei, Taiwan' },
  { value: 'thimphu_bhutan', label: 'Thimphu, Bhutan' },
  { value: 'tokyo_japan', label: 'Tokyo, Japan' },
  { value: 'wuhan_china', label: 'Wuhan, China' },

  // NORTH AMERICA - United States
  { value: 'new_york_usa', label: 'New York, USA' },
  { value: 'los_angeles_usa', label: 'Los Angeles, USA' },
  { value: 'chicago_usa', label: 'Chicago, USA' },
  { value: 'houston_usa', label: 'Houston, USA' },
  { value: 'phoenix_usa', label: 'Phoenix, USA' },
  { value: 'philadelphia_usa', label: 'Philadelphia, USA' },
  { value: 'san_antonio_usa', label: 'San Antonio, USA' },
  { value: 'san_diego_usa', label: 'San Diego, USA' },
  { value: 'dallas_usa', label: 'Dallas, USA' },
  { value: 'san_jose_usa', label: 'San Jose, USA' },
  { value: 'austin_usa', label: 'Austin, USA' },
  { value: 'jacksonville_usa', label: 'Jacksonville, USA' },
  { value: 'fort_worth_usa', label: 'Fort Worth, USA' },
  { value: 'columbus_usa', label: 'Columbus, USA' },
  { value: 'charlotte_usa', label: 'Charlotte, USA' },
  { value: 'san_francisco_usa', label: 'San Francisco, USA' },
  { value: 'indianapolis_usa', label: 'Indianapolis, USA' },
  { value: 'seattle_usa', label: 'Seattle, USA' },
  { value: 'denver_usa', label: 'Denver, USA' },
  { value: 'washington_dc_usa', label: 'Washington DC, USA' },
  { value: 'boston_usa', label: 'Boston, USA' },
  { value: 'las_vegas_usa', label: 'Las Vegas, USA' },
  { value: 'detroit_usa', label: 'Detroit, USA' },
  { value: 'nashville_usa', label: 'Nashville, USA' },
  { value: 'portland_usa', label: 'Portland, USA' },
  { value: 'miami_usa', label: 'Miami, USA' },
  { value: 'atlanta_usa', label: 'Atlanta, USA' },
  { value: 'orlando_usa', label: 'Orlando, USA' },
  { value: 'minneapolis_usa', label: 'Minneapolis, USA' },
  { value: 'new_orleans_usa', label: 'New Orleans, USA' },

  // NORTH AMERICA - Canada
  { value: 'toronto_canada', label: 'Toronto, Canada' },
  { value: 'montreal_canada', label: 'Montreal, Canada' },
  { value: 'vancouver_canada', label: 'Vancouver, Canada' },
  { value: 'calgary_canada', label: 'Calgary, Canada' },
  { value: 'ottawa_canada', label: 'Ottawa, Canada' },
  { value: 'edmonton_canada', label: 'Edmonton, Canada' },
  { value: 'winnipeg_canada', label: 'Winnipeg, Canada' },
  { value: 'quebec_city_canada', label: 'Quebec City, Canada' },
  { value: 'hamilton_canada', label: 'Hamilton, Canada' },
  { value: 'halifax_canada', label: 'Halifax, Canada' },

  // NORTH AMERICA - Mexico
  { value: 'mexico_city_mexico', label: 'Mexico City, Mexico' },
  { value: 'guadalajara_mexico', label: 'Guadalajara, Mexico' },
  { value: 'monterrey_mexico', label: 'Monterrey, Mexico' },
  { value: 'puebla_mexico', label: 'Puebla, Mexico' },
  { value: 'tijuana_mexico', label: 'Tijuana, Mexico' },
  { value: 'leon_mexico', label: 'Leon, Mexico' },
  { value: 'juarez_mexico', label: 'Juarez, Mexico' },
  { value: 'zapopan_mexico', label: 'Zapopan, Mexico' },
  { value: 'nezahualcoyotl_mexico', label: 'Nezahualcoyotl, Mexico' },
  { value: 'cancun_mexico', label: 'Cancun, Mexico' },

  // EUROPE - United Kingdom
  { value: 'london_uk', label: 'London, UK' },
  { value: 'birmingham_uk', label: 'Birmingham, UK' },
  { value: 'manchester_uk', label: 'Manchester, UK' },
  { value: 'glasgow_uk', label: 'Glasgow, UK' },
  { value: 'edinburgh_uk', label: 'Edinburgh, UK' },
  { value: 'liverpool_uk', label: 'Liverpool, UK' },
  { value: 'bristol_uk', label: 'Bristol, UK' },
  { value: 'leeds_uk', label: 'Leeds, UK' },
  { value: 'cardiff_uk', label: 'Cardiff, UK' },
  { value: 'belfast_uk', label: 'Belfast, UK' },

  // EUROPE - France
  { value: 'paris_france', label: 'Paris, France' },
  { value: 'marseille_france', label: 'Marseille, France' },
  { value: 'lyon_france', label: 'Lyon, France' },
  { value: 'toulouse_france', label: 'Toulouse, France' },
  { value: 'nice_france', label: 'Nice, France' },
  { value: 'nantes_france', label: 'Nantes, France' },
  { value: 'strasbourg_france', label: 'Strasbourg, France' },
  { value: 'montpellier_france', label: 'Montpellier, France' },
  { value: 'bordeaux_france', label: 'Bordeaux, France' },
  { value: 'lille_france', label: 'Lille, France' },

  // EUROPE - Germany
  { value: 'berlin_germany', label: 'Berlin, Germany' },
  { value: 'hamburg_germany', label: 'Hamburg, Germany' },
  { value: 'munich_germany', label: 'Munich, Germany' },
  { value: 'cologne_germany', label: 'Cologne, Germany' },
  { value: 'frankfurt_germany', label: 'Frankfurt, Germany' },
  { value: 'stuttgart_germany', label: 'Stuttgart, Germany' },
  { value: 'dusseldorf_germany', label: 'Dusseldorf, Germany' },
  { value: 'dortmund_germany', label: 'Dortmund, Germany' },
  { value: 'essen_germany', label: 'Essen, Germany' },
  { value: 'leipzig_germany', label: 'Leipzig, Germany' },

  // EUROPE - Italy
  { value: 'rome_italy', label: 'Rome, Italy' },
  { value: 'milan_italy', label: 'Milan, Italy' },
  { value: 'naples_italy', label: 'Naples, Italy' },
  { value: 'turin_italy', label: 'Turin, Italy' },
  { value: 'palermo_italy', label: 'Palermo, Italy' },
  { value: 'genoa_italy', label: 'Genoa, Italy' },
  { value: 'bologna_italy', label: 'Bologna, Italy' },
  { value: 'florence_italy', label: 'Florence, Italy' },
  { value: 'bari_italy', label: 'Bari, Italy' },
  { value: 'catania_italy', label: 'Catania, Italy' },

  // EUROPE - Spain
  { value: 'madrid_spain', label: 'Madrid, Spain' },
  { value: 'barcelona_spain', label: 'Barcelona, Spain' },
  { value: 'valencia_spain', label: 'Valencia, Spain' },
  { value: 'seville_spain', label: 'Seville, Spain' },
  { value: 'zaragoza_spain', label: 'Zaragoza, Spain' },
  { value: 'malaga_spain', label: 'Malaga, Spain' },
  { value: 'murcia_spain', label: 'Murcia, Spain' },
  { value: 'palma_spain', label: 'Palma, Spain' },
  { value: 'bilbao_spain', label: 'Bilbao, Spain' },
  { value: 'alicante_spain', label: 'Alicante, Spain' },

  // EUROPE - Netherlands
  { value: 'amsterdam_netherlands', label: 'Amsterdam, Netherlands' },
  { value: 'rotterdam_netherlands', label: 'Rotterdam, Netherlands' },
  { value: 'hague_netherlands', label: 'The Hague, Netherlands' },
  { value: 'utrecht_netherlands', label: 'Utrecht, Netherlands' },
  { value: 'eindhoven_netherlands', label: 'Eindhoven, Netherlands' },
  { value: 'tilburg_netherlands', label: 'Tilburg, Netherlands' },
  { value: 'groningen_netherlands', label: 'Groningen, Netherlands' },

  // EUROPE - Other European Countries
  { value: 'vienna_austria', label: 'Vienna, Austria' },
  { value: 'brussels_belgium', label: 'Brussels, Belgium' },
  { value: 'antwerp_belgium', label: 'Antwerp, Belgium' },
  { value: 'zurich_switzerland', label: 'Zurich, Switzerland' },
  { value: 'geneva_switzerland', label: 'Geneva, Switzerland' },
  { value: 'copenhagen_denmark', label: 'Copenhagen, Denmark' },
  { value: 'stockholm_sweden', label: 'Stockholm, Sweden' },
  { value: 'oslo_norway', label: 'Oslo, Norway' },
  { value: 'helsinki_finland', label: 'Helsinki, Finland' },
  { value: 'dublin_ireland', label: 'Dublin, Ireland' },
  { value: 'lisbon_portugal', label: 'Lisbon, Portugal' },
  { value: 'porto_portugal', label: 'Porto, Portugal' },
  { value: 'athens_greece', label: 'Athens, Greece' },
  { value: 'thessaloniki_greece', label: 'Thessaloniki, Greece' },
  { value: 'warsaw_poland', label: 'Warsaw, Poland' },
  { value: 'krakow_poland', label: 'Krakow, Poland' },
  { value: 'prague_czech_republic', label: 'Prague, Czech Republic' },
  { value: 'budapest_hungary', label: 'Budapest, Hungary' },
  { value: 'bucharest_romania', label: 'Bucharest, Romania' },
  { value: 'sofia_bulgaria', label: 'Sofia, Bulgaria' },
  { value: 'zagreb_croatia', label: 'Zagreb, Croatia' },
  { value: 'belgrade_serbia', label: 'Belgrade, Serbia' },
  { value: 'ljubljana_slovenia', label: 'Ljubljana, Slovenia' },
  { value: 'bratislava_slovakia', label: 'Bratislava, Slovakia' },
  { value: 'vilnius_lithuania', label: 'Vilnius, Lithuania' },
  { value: 'riga_latvia', label: 'Riga, Latvia' },
  { value: 'tallinn_estonia', label: 'Tallinn, Estonia' },
  { value: 'kiev_ukraine', label: 'Kiev, Ukraine' },
  { value: 'minsk_belarus', label: 'Minsk, Belarus' },
  { value: 'moscow_russia', label: 'Moscow, Russia' },
  { value: 'saint_petersburg_russia', label: 'Saint Petersburg, Russia' },
  { value: 'novosibirsk_russia', label: 'Novosibirsk, Russia' },
  { value: 'yekaterinburg_russia', label: 'Yekaterinburg, Russia' },
  { value: 'nizhny_novgorod_russia', label: 'Nizhny Novgorod, Russia' },
  { value: 'kazan_russia', label: 'Kazan, Russia' },
  { value: 'chelyabinsk_russia', label: 'Chelyabinsk, Russia' },
  { value: 'omsk_russia', label: 'Omsk, Russia' },
  { value: 'samara_russia', label: 'Samara, Russia' },
  { value: 'rostov_on_don_russia', label: 'Rostov-on-Don, Russia' },
  { value: 'ufa_russia', label: 'Ufa, Russia' },
  { value: 'krasnoyarsk_russia', label: 'Krasnoyarsk, Russia' },
  { value: 'perm_russia', label: 'Perm, Russia' },
  { value: 'voronezh_russia', label: 'Voronezh, Russia' },
  { value: 'volgograd_russia', label: 'Volgograd, Russia' },
  { value: 'krasnodar_russia', label: 'Krasnodar, Russia' },
  { value: 'vladivostok_russia', label: 'Vladivostok, Russia' },
  { value: 'irkutsk_russia', label: 'Irkutsk, Russia' },

  // SOUTH AMERICA - Brazil
  { value: 'sao_paulo_brazil', label: 'São Paulo, Brazil' },
  { value: 'rio_de_janeiro_brazil', label: 'Rio de Janeiro, Brazil' },
  { value: 'brasilia_brazil', label: 'Brasília, Brazil' },
  { value: 'salvador_brazil', label: 'Salvador, Brazil' },
  { value: 'fortaleza_brazil', label: 'Fortaleza, Brazil' },
  { value: 'belo_horizonte_brazil', label: 'Belo Horizonte, Brazil' },
  { value: 'manaus_brazil', label: 'Manaus, Brazil' },
  { value: 'curitiba_brazil', label: 'Curitiba, Brazil' },
  { value: 'recife_brazil', label: 'Recife, Brazil' },
  { value: 'porto_alegre_brazil', label: 'Porto Alegre, Brazil' },
  { value: 'goiania_brazil', label: 'Goiânia, Brazil' },
  { value: 'belém_brazil', label: 'Belém, Brazil' },
  { value: 'guarulhos_brazil', label: 'Guarulhos, Brazil' },
  { value: 'campinas_brazil', label: 'Campinas, Brazil' },
  { value: 'natal_brazil', label: 'Natal, Brazil' },

  // SOUTH AMERICA - Argentina
  { value: 'buenos_aires_argentina', label: 'Buenos Aires, Argentina' },
  { value: 'cordoba_argentina', label: 'Córdoba, Argentina' },
  { value: 'rosario_argentina', label: 'Rosario, Argentina' },
  { value: 'mendoza_argentina', label: 'Mendoza, Argentina' },
  { value: 'tucuman_argentina', label: 'Tucumán, Argentina' },
  { value: 'la_plata_argentina', label: 'La Plata, Argentina' },
  { value: 'mar_del_plata_argentina', label: 'Mar del Plata, Argentina' },
  { value: 'salta_argentina', label: 'Salta, Argentina' },
  { value: 'santa_fe_argentina', label: 'Santa Fe, Argentina' },
  { value: 'san_juan_argentina', label: 'San Juan, Argentina' },

  // SOUTH AMERICA - Other Countries
  { value: 'bogota_colombia', label: 'Bogotá, Colombia' },
  { value: 'medellin_colombia', label: 'Medellín, Colombia' },
  { value: 'cali_colombia', label: 'Cali, Colombia' },
  { value: 'barranquilla_colombia', label: 'Barranquilla, Colombia' },
  { value: 'cartagena_colombia', label: 'Cartagena, Colombia' },
  { value: 'lima_peru', label: 'Lima, Peru' },
  { value: 'arequipa_peru', label: 'Arequipa, Peru' },
  { value: 'trujillo_peru', label: 'Trujillo, Peru' },
  { value: 'cusco_peru', label: 'Cusco, Peru' },
  { value: 'santiago_chile', label: 'Santiago, Chile' },
  { value: 'valparaiso_chile', label: 'Valparaíso, Chile' },
  { value: 'concepcion_chile', label: 'Concepción, Chile' },
  { value: 'antofagasta_chile', label: 'Antofagasta, Chile' },
  { value: 'caracas_venezuela', label: 'Caracas, Venezuela' },
  { value: 'maracaibo_venezuela', label: 'Maracaibo, Venezuela' },
  { value: 'valencia_venezuela', label: 'Valencia, Venezuela' },
  { value: 'quito_ecuador', label: 'Quito, Ecuador' },
  { value: 'guayaquil_ecuador', label: 'Guayaquil, Ecuador' },
  { value: 'la_paz_bolivia', label: 'La Paz, Bolivia' },
  { value: 'santa_cruz_bolivia', label: 'Santa Cruz, Bolivia' },
  { value: 'asuncion_paraguay', label: 'Asunción, Paraguay' },
  { value: 'montevideo_uruguay', label: 'Montevideo, Uruguay' },
  { value: 'georgetown_guyana', label: 'Georgetown, Guyana' },
  { value: 'paramaribo_suriname', label: 'Paramaribo, Suriname' },
  { value: 'cayenne_french_guiana', label: 'Cayenne, French Guiana' },

  // AFRICA - North Africa
  { value: 'cairo_egypt', label: 'Cairo, Egypt' },
  { value: 'alexandria_egypt', label: 'Alexandria, Egypt' },
  { value: 'giza_egypt', label: 'Giza, Egypt' },
  { value: 'shubra_el_kheima_egypt', label: 'Shubra El Kheima, Egypt' },
  { value: 'port_said_egypt', label: 'Port Said, Egypt' },
  { value: 'suez_egypt', label: 'Suez, Egypt' },
  { value: 'casablanca_morocco', label: 'Casablanca, Morocco' },
  { value: 'rabat_morocco', label: 'Rabat, Morocco' },
  { value: 'fes_morocco', label: 'Fes, Morocco' },
  { value: 'marrakech_morocco', label: 'Marrakech, Morocco' },
  { value: 'agadir_morocco', label: 'Agadir, Morocco' },
  { value: 'tangier_morocco', label: 'Tangier, Morocco' },
  { value: 'algiers_algeria', label: 'Algiers, Algeria' },
  { value: 'oran_algeria', label: 'Oran, Algeria' },
  { value: 'constantine_algeria', label: 'Constantine, Algeria' },
  { value: 'annaba_algeria', label: 'Annaba, Algeria' },
  { value: 'tunis_tunisia', label: 'Tunis, Tunisia' },
  { value: 'sfax_tunisia', label: 'Sfax, Tunisia' },
  { value: 'sousse_tunisia', label: 'Sousse, Tunisia' },
  { value: 'tripoli_libya', label: 'Tripoli, Libya' },
  { value: 'benghazi_libya', label: 'Benghazi, Libya' },
  { value: 'khartoum_sudan', label: 'Khartoum, Sudan' },
  { value: 'omdurman_sudan', label: 'Omdurman, Sudan' },
  { value: 'port_sudan_sudan', label: 'Port Sudan, Sudan' },

  // AFRICA - West Africa
  { value: 'lagos_nigeria', label: 'Lagos, Nigeria' },
  { value: 'kano_nigeria', label: 'Kano, Nigeria' },
  { value: 'ibadan_nigeria', label: 'Ibadan, Nigeria' },
  { value: 'abuja_nigeria', label: 'Abuja, Nigeria' },
  { value: 'port_harcourt_nigeria', label: 'Port Harcourt, Nigeria' },
  { value: 'benin_city_nigeria', label: 'Benin City, Nigeria' },
  { value: 'maiduguri_nigeria', label: 'Maiduguri, Nigeria' },
  { value: 'zaria_nigeria', label: 'Zaria, Nigeria' },
  { value: 'aba_nigeria', label: 'Aba, Nigeria' },
  { value: 'jos_nigeria', label: 'Jos, Nigeria' },
  { value: 'accra_ghana', label: 'Accra, Ghana' },
  { value: 'kumasi_ghana', label: 'Kumasi, Ghana' },
  { value: 'tamale_ghana', label: 'Tamale, Ghana' },
  { value: 'abidjan_ivory_coast', label: 'Abidjan, Ivory Coast' },
  { value: 'yamoussoukro_ivory_coast', label: 'Yamoussoukro, Ivory Coast' },
  { value: 'dakar_senegal', label: 'Dakar, Senegal' },
  { value: 'touba_senegal', label: 'Touba, Senegal' },
  { value: 'ouagadougou_burkina_faso', label: 'Ouagadougou, Burkina Faso' },
  { value: 'bamako_mali', label: 'Bamako, Mali' },
  { value: 'conakry_guinea', label: 'Conakry, Guinea' },
  { value: 'freetown_sierra_leone', label: 'Freetown, Sierra Leone' },
  { value: 'monrovia_liberia', label: 'Monrovia, Liberia' },
  { value: 'lome_togo', label: 'Lomé, Togo' },
  { value: 'cotonou_benin', label: 'Cotonou, Benin' },
  { value: 'porto_novo_benin', label: 'Porto-Novo, Benin' },
  { value: 'niamey_niger', label: 'Niamey, Niger' },
  { value: 'nouakchott_mauritania', label: 'Nouakchott, Mauritania' },

  // AFRICA - East Africa
  { value: 'addis_ababa_ethiopia', label: 'Addis Ababa, Ethiopia' },
  { value: 'dire_dawa_ethiopia', label: 'Dire Dawa, Ethiopia' },
  { value: 'mekelle_ethiopia', label: 'Mekelle, Ethiopia' },
  { value: 'nairobi_kenya', label: 'Nairobi, Kenya' },
  { value: 'mombasa_kenya', label: 'Mombasa, Kenya' },
  { value: 'kisumu_kenya', label: 'Kisumu, Kenya' },
  { value: 'nakuru_kenya', label: 'Nakuru, Kenya' },
  { value: 'kampala_uganda', label: 'Kampala, Uganda' },
  { value: 'gulu_uganda', label: 'Gulu, Uganda' },
  { value: 'dar_es_salaam_tanzania', label: 'Dar es Salaam, Tanzania' },
  { value: 'mwanza_tanzania', label: 'Mwanza, Tanzania' },
  { value: 'arusha_tanzania', label: 'Arusha, Tanzania' },
  { value: 'dodoma_tanzania', label: 'Dodoma, Tanzania' },
  { value: 'kigali_rwanda', label: 'Kigali, Rwanda' },
  { value: 'bujumbura_burundi', label: 'Bujumbura, Burundi' },
  { value: 'mogadishu_somalia', label: 'Mogadishu, Somalia' },
  { value: 'hargeisa_somalia', label: 'Hargeisa, Somalia' },
  { value: 'djibouti_city_djibouti', label: 'Djibouti City, Djibouti' },
  { value: 'asmara_eritrea', label: 'Asmara, Eritrea' },

  // AFRICA - Central Africa
  { value: 'kinshasa_congo_drc', label: 'Kinshasa, Congo (DRC)' },
  { value: 'lubumbashi_congo_drc', label: 'Lubumbashi, Congo (DRC)' },
  { value: 'mbuji_mayi_congo_drc', label: 'Mbuji-Mayi, Congo (DRC)' },
  { value: 'kisangani_congo_drc', label: 'Kisangani, Congo (DRC)' },
  { value: 'brazzaville_congo', label: 'Brazzaville, Congo' },
  { value: 'pointe_noire_congo', label: 'Pointe-Noire, Congo' },
  { value: 'yaoundé_cameroon', label: 'Yaoundé, Cameroon' },
  { value: 'douala_cameroon', label: 'Douala, Cameroon' },
  { value: 'garoua_cameroon', label: 'Garoua, Cameroon' },
  { value: 'bangui_central_african_republic', label: 'Bangui, Central African Republic' },
  { value: 'ndjamena_chad', label: "N'Djamena, Chad" },
  { value: 'libreville_gabon', label: 'Libreville, Gabon' },
  { value: 'port_gentil_gabon', label: 'Port-Gentil, Gabon' },
  { value: 'malabo_equatorial_guinea', label: 'Malabo, Equatorial Guinea' },
  { value: 'sao_tome_sao_tome_principe', label: 'São Tomé, São Tomé and Príncipe' },

  // AFRICA - Southern Africa
  { value: 'johannesburg_south_africa', label: 'Johannesburg, South Africa' },
  { value: 'cape_town_south_africa', label: 'Cape Town, South Africa' },
  { value: 'durban_south_africa', label: 'Durban, South Africa' },
  { value: 'pretoria_south_africa', label: 'Pretoria, South Africa' },
  { value: 'port_elizabeth_south_africa', label: 'Port Elizabeth, South Africa' },
  { value: 'bloemfontein_south_africa', label: 'Bloemfontein, South Africa' },
  { value: 'east_london_south_africa', label: 'East London, South Africa' },
  { value: 'pietermaritzburg_south_africa', label: 'Pietermaritzburg, South Africa' },
  { value: 'nelspruit_south_africa', label: 'Nelspruit, South Africa' },
  { value: 'kimberley_south_africa', label: 'Kimberley, South Africa' },
  { value: 'luanda_angola', label: 'Luanda, Angola' },
  { value: 'huambo_angola', label: 'Huambo, Angola' },
  { value: 'lobito_angola', label: 'Lobito, Angola' },
  { value: 'maputo_mozambique', label: 'Maputo, Mozambique' },
  { value: 'matola_mozambique', label: 'Matola, Mozambique' },
  { value: 'beira_mozambique', label: 'Beira, Mozambique' },
  { value: 'nampula_mozambique', label: 'Nampula, Mozambique' },
  { value: 'lusaka_zambia', label: 'Lusaka, Zambia' },
  { value: 'kitwe_zambia', label: 'Kitwe, Zambia' },
  { value: 'ndola_zambia', label: 'Ndola, Zambia' },
  { value: 'harare_zimbabwe', label: 'Harare, Zimbabwe' },
  { value: 'bulawayo_zimbabwe', label: 'Bulawayo, Zimbabwe' },
  { value: 'chitungwiza_zimbabwe', label: 'Chitungwiza, Zimbabwe' },
  { value: 'gaborone_botswana', label: 'Gaborone, Botswana' },
  { value: 'francistown_botswana', label: 'Francistown, Botswana' },
  { value: 'windhoek_namibia', label: 'Windhoek, Namibia' },
  { value: 'walvis_bay_namibia', label: 'Walvis Bay, Namibia' },
  { value: 'mbabane_swaziland', label: 'Mbabane, Swaziland' },
  { value: 'maseru_lesotho', label: 'Maseru, Lesotho' },
  { value: 'port_louis_mauritius', label: 'Port Louis, Mauritius' },
  { value: 'beau_bassin_mauritius', label: 'Beau Bassin, Mauritius' },
  { value: 'victoria_seychelles', label: 'Victoria, Seychelles' },
  { value: 'antananarivo_madagascar', label: 'Antananarivo, Madagascar' },
  { value: 'toamasina_madagascar', label: 'Toamasina, Madagascar' },
  { value: 'antsirabe_madagascar', label: 'Antsirabe, Madagascar' },
  { value: 'saint_denis_reunion', label: 'Saint-Denis, Réunion' },
  { value: 'saint_paul_reunion', label: 'Saint-Paul, Réunion' },
  { value: 'moroni_comoros', label: 'Moroni, Comoros' },

  // OCEANIA - Australia
  { value: 'sydney_australia', label: 'Sydney, Australia' },
  { value: 'melbourne_australia', label: 'Melbourne, Australia' },
  { value: 'brisbane_australia', label: 'Brisbane, Australia' },
  { value: 'perth_australia', label: 'Perth, Australia' },
  { value: 'adelaide_australia', label: 'Adelaide, Australia' },
  { value: 'gold_coast_australia', label: 'Gold Coast, Australia' },
  { value: 'newcastle_australia', label: 'Newcastle, Australia' },
  { value: 'canberra_australia', label: 'Canberra, Australia' },
  { value: 'sunshine_coast_australia', label: 'Sunshine Coast, Australia' },
  { value: 'wollongong_australia', label: 'Wollongong, Australia' },
  { value: 'hobart_australia', label: 'Hobart, Australia' },
  { value: 'geelong_australia', label: 'Geelong, Australia' },
  { value: 'townsville_australia', label: 'Townsville, Australia' },
  { value: 'cairns_australia', label: 'Cairns, Australia' },
  { value: 'darwin_australia', label: 'Darwin, Australia' },
  { value: 'toowoomba_australia', label: 'Toowoomba, Australia' },
  { value: 'ballarat_australia', label: 'Ballarat, Australia' },
  { value: 'bendigo_australia', label: 'Bendigo, Australia' },
  { value: 'albury_australia', label: 'Albury, Australia' },
  { value: 'launceston_australia', label: 'Launceston, Australia' },

  // OCEANIA - New Zealand
  { value: 'auckland_new_zealand', label: 'Auckland, New Zealand' },
  { value: 'christchurch_new_zealand', label: 'Christchurch, New Zealand' },
  { value: 'wellington_new_zealand', label: 'Wellington, New Zealand' },
  { value: 'hamilton_new_zealand', label: 'Hamilton, New Zealand' },
  { value: 'tauranga_new_zealand', label: 'Tauranga, New Zealand' },
  { value: 'napier_new_zealand', label: 'Napier, New Zealand' },
  { value: 'dunedin_new_zealand', label: 'Dunedin, New Zealand' },
  { value: 'palmerston_north_new_zealand', label: 'Palmerston North, New Zealand' },
  { value: 'nelson_new_zealand', label: 'Nelson, New Zealand' },
  { value: 'rotorua_new_zealand', label: 'Rotorua, New Zealand' },
  { value: 'new_plymouth_new_zealand', label: 'New Plymouth, New Zealand' },
  { value: 'whangarei_new_zealand', label: 'Whangarei, New Zealand' },
  { value: 'invercargill_new_zealand', label: 'Invercargill, New Zealand' },

  // OCEANIA - Pacific Islands
  { value: 'suva_fiji', label: 'Suva, Fiji' },
  { value: 'lautoka_fiji', label: 'Lautoka, Fiji' },
  { value: 'nadi_fiji', label: 'Nadi, Fiji' },
  { value: 'port_moresby_papua_new_guinea', label: 'Port Moresby, Papua New Guinea' },
  { value: 'lae_papua_new_guinea', label: 'Lae, Papua New Guinea' },
  { value: 'mount_hagen_papua_new_guinea', label: 'Mount Hagen, Papua New Guinea' },
  { value: 'port_vila_vanuatu', label: 'Port Vila, Vanuatu' },
  { value: 'luganville_vanuatu', label: 'Luganville, Vanuatu' },
  { value: 'noumea_new_caledonia', label: 'Nouméa, New Caledonia' },
  { value: 'mont_dore_new_caledonia', label: 'Mont-Dore, New Caledonia' },
  { value: 'apia_samoa', label: 'Apia, Samoa' },
  { value: 'nukualofa_tonga', label: "Nuku'alofa, Tonga" },
  { value: 'majuro_marshall_islands', label: 'Majuro, Marshall Islands' },
  { value: 'tarawa_kiribati', label: 'Tarawa, Kiribati' },
  { value: 'funafuti_tuvalu', label: 'Funafuti, Tuvalu' },
  { value: 'ngerulmud_palau', label: 'Ngerulmud, Palau' },
  { value: 'palikir_micronesia', label: 'Palikir, Micronesia' },
  { value: 'yaren_nauru', label: 'Yaren, Nauru' },
  { value: 'honiara_solomon_islands', label: 'Honiara, Solomon Islands' },
  { value: 'papeete_french_polynesia', label: 'Papeete, French Polynesia' },
  { value: 'faaa_french_polynesia', label: 'Faaa, French Polynesia' },
  { value: 'avarua_cook_islands', label: 'Avarua, Cook Islands' },

  // ANTARCTICA - Research Stations
  { value: 'mcmurdo_station_antarctica', label: 'McMurdo Station, Antarctica' },
  { value: 'rothera_station_antarctica', label: 'Rothera Station, Antarctica' },
  { value: 'esperanza_base_antarctica', label: 'Esperanza Base, Antarctica' },
  { value: 'vostok_station_antarctica', label: 'Vostok Station, Antarctica' },
  { value: 'halley_station_antarctica', label: 'Halley Station, Antarctica' },
  { value: 'davis_station_antarctica', label: 'Davis Station, Antarctica' },
  { value: 'casey_station_antarctica', label: 'Casey Station, Antarctica' },
  { value: 'mawson_station_antarctica', label: 'Mawson Station, Antarctica' },
  { value: 'belgrano_ii_base_antarctica', label: 'Belgrano II Base, Antarctica' },
  { value: 'scott_base_antarctica', label: 'Scott Base, Antarctica' },
  { value: 'palmer_station_antarctica', label: 'Palmer Station, Antarctica' },
  { value: 'dumont_durville_station_antarctica', label: "Dumont d'Urville Station, Antarctica" },
  { value: 'sanae_station_antarctica', label: 'SANAE Station, Antarctica' },
  { value: 'troll_station_antarctica', label: 'Troll Station, Antarctica' },
  { value: 'orcadas_base_antarctica', label: 'Orcadas Base, Antarctica' },

  // CENTRAL ASIA - Additional Countries
  { value: 'almaty_kazakhstan', label: 'Almaty, Kazakhstan' },
  { value: 'nur_sultan_kazakhstan', label: 'Nur-Sultan, Kazakhstan' },
  { value: 'shymkent_kazakhstan', label: 'Shymkent, Kazakhstan' },
  { value: 'tashkent_uzbekistan', label: 'Tashkent, Uzbekistan' },
  { value: 'samarkand_uzbekistan', label: 'Samarkand, Uzbekistan' },
  { value: 'namangan_uzbekistan', label: 'Namangan, Uzbekistan' },
  { value: 'bishkek_kyrgyzstan', label: 'Bishkek, Kyrgyzstan' },
  { value: 'osh_kyrgyzstan', label: 'Osh, Kyrgyzstan' },
  { value: 'dushanbe_tajikistan', label: 'Dushanbe, Tajikistan' },
  { value: 'khujand_tajikistan', label: 'Khujand, Tajikistan' },
  { value: 'ashgabat_turkmenistan', label: 'Ashgabat, Turkmenistan' },
  { value: 'turkmenbashi_turkmenistan', label: 'Turkmenbashi, Turkmenistan' },
  { value: 'baku_azerbaijan', label: 'Baku, Azerbaijan' },
  { value: 'ganja_azerbaijan', label: 'Ganja, Azerbaijan' },
  { value: 'sumgayit_azerbaijan', label: 'Sumgayit, Azerbaijan' },
  { value: 'yerevan_armenia', label: 'Yerevan, Armenia' },
  { value: 'gyumri_armenia', label: 'Gyumri, Armenia' },
  { value: 'vanadzor_armenia', label: 'Vanadzor, Armenia' },
  { value: 'tbilisi_georgia', label: 'Tbilisi, Georgia' },
  { value: 'batumi_georgia', label: 'Batumi, Georgia' },
  { value: 'kutaisi_georgia', label: 'Kutaisi, Georgia' },
  { value: 'sukhumi_georgia', label: 'Sukhumi, Georgia' },

  // CARIBBEAN - Major Islands
  { value: 'havana_cuba', label: 'Havana, Cuba' },
  { value: 'santiago_cuba', label: 'Santiago de Cuba, Cuba' },
  { value: 'camaguey_cuba', label: 'Camagüey, Cuba' },
  { value: 'kingston_jamaica', label: 'Kingston, Jamaica' },
  { value: 'spanish_town_jamaica', label: 'Spanish Town, Jamaica' },
  { value: 'montego_bay_jamaica', label: 'Montego Bay, Jamaica' },
  { value: 'santo_domingo_dominican_republic', label: 'Santo Domingo, Dominican Republic' },
  { value: 'santiago_dominican_republic', label: 'Santiago, Dominican Republic' },
  { value: 'port_au_prince_haiti', label: 'Port-au-Prince, Haiti' },
  { value: 'cap_haitien_haiti', label: 'Cap-Haïtien, Haiti' },
  { value: 'san_juan_puerto_rico', label: 'San Juan, Puerto Rico' },
  { value: 'bayamon_puerto_rico', label: 'Bayamón, Puerto Rico' },
  { value: 'bridgetown_barbados', label: 'Bridgetown, Barbados' },
  { value: 'port_of_spain_trinidad_tobago', label: 'Port of Spain, Trinidad and Tobago' },
  { value: 'nassau_bahamas', label: 'Nassau, Bahamas' },
  { value: 'belize_city_belize', label: 'Belize City, Belize' },
  { value: 'belmopan_belize', label: 'Belmopan, Belize' },

    // ASIA - Southeast Asia
    { value: 'bandung_indonesia', label: 'Bandung, Indonesia' },
    { value: 'medan_indonesia', label: 'Medan, Indonesia' },
    { value: 'makassar_indonesia', label: 'Makassar, Indonesia' },
    { value: 'pattaya_thailand', label: 'Pattaya, Thailand' },
    { value: 'chiang_mai_thailand', label: 'Chiang Mai, Thailand' },
    { value: 'kota_kinabalu_malaysia', label: 'Kota Kinabalu, Malaysia' },
    { value: 'george_town_malaysia', label: 'George Town, Malaysia' },
    { value: 'da_nang_vietnam', label: 'Da Nang, Vietnam' },
    { value: 'can_tho_vietnam', label: 'Can Tho, Vietnam' },
    { value: 'cebu_city_philippines', label: 'Cebu City, Philippines' },
    { value: 'davao_city_philippines', label: 'Davao City, Philippines' },
    { value: 'naypyidaw_myanmar', label: 'Naypyidaw, Myanmar' },
    { value: 'mandalay_myanmar', label: 'Mandalay, Myanmar' },
  
    // ASIA - South Asia
    { value: 'chittagong_bangladesh', label: 'Chittagong, Bangladesh' },
    { value: 'rajshahi_bangladesh', label: 'Rajshahi, Bangladesh' },
    { value: 'pune_india', label: 'Pune, India' },
    { value: 'surat_india', label: 'Surat, India' },
    { value: 'jaipur_india', label: 'Jaipur, India' },
    { value: 'lucknow_india', label: 'Lucknow, India' },
    { value: 'nagpur_india', label: 'Nagpur, India' },
    { value: 'visakhapatnam_india', label: 'Visakhapatnam, India' },
    { value: 'faisalabad_pakistan', label: 'Faisalabad, Pakistan' },
    { value: 'rawalpindi_pakistan', label: 'Rawalpindi, Pakistan' },
    { value: 'kandy_sri_lanka', label: 'Kandy, Sri Lanka' },
    { value: 'galle_sri_lanka', label: 'Galle, Sri Lanka' },
    { value: 'malé_maldives', label: 'Malé, Maldives' },
    { value: 'pokhara_nepal', label: 'Pokhara, Nepal' },
  
    // ASIA - East Asia
    { value: 'fukuoka_japan', label: 'Fukuoka, Japan' },
    { value: 'sapporo_japan', label: 'Sapporo, Japan' },
    { value: 'sendai_japan', label: 'Sendai, Japan' },
    { value: 'guangzhou_china', label: 'Guangzhou, China' },
    { value: 'shenzhen_china', label: 'Shenzhen, China' },
    { value: 'chengdu_china', label: 'Chengdu, China' },
    { value: 'hangzhou_china', label: 'Hangzhou, China' },
    { value: 'taipei_taiwan', label: 'Taipei, Taiwan' },
    { value: 'tainan_taiwan', label: 'Tainan, Taiwan' },
    { value: 'busan_south_korea', label: 'Busan, South Korea' },
    { value: 'incheon_south_korea', label: 'Incheon, South Korea' },
    { value: 'darkhan_mongolia', label: 'Darkhan, Mongolia' },
  
    // AFRICA - North Africa
    { value: 'alexandria_egypt', label: 'Alexandria, Egypt' },
    { value: 'giza_egypt', label: 'Giza, Egypt' },
    { value: 'tangier_morocco', label: 'Tangier, Morocco' },
    { value: 'agadir_morocco', label: 'Agadir, Morocco' },
    { value: 'oran_algeria', label: 'Oran, Algeria' },
    { value: 'constantine_algeria', label: 'Constantine, Algeria' },
    { value: 'sousse_tunisia', label: 'Sousse, Tunisia' },
    { value: 'sfax_tunisia', label: 'Sfax, Tunisia' },
    { value: 'benghazi_libya', label: 'Benghazi, Libya' },
    { value: 'khartoum_sudan', label: 'Khartoum, Sudan' },
    { value: 'omdurman_sudan', label: 'Omdurman, Sudan' },
  
    // AFRICA - West Africa
    { value: 'lagos_nigeria', label: 'Lagos, Nigeria' },
    { value: 'ibadan_nigeria', label: 'Ibadan, Nigeria' },
    { value: 'abuja_nigeria', label: 'Abuja, Nigeria' },
    { value: 'accra_ghana', label: 'Accra, Ghana' },
    { value: 'kumasi_ghana', label: 'Kumasi, Ghana' },
    { value: 'abidjan_ivory_coast', label: 'Abidjan, Ivory Coast' },
    { value: 'yamoussoukro_ivory_coast', label: 'Yamoussoukro, Ivory Coast' },
    { value: 'dakar_senegal', label: 'Dakar, Senegal' },
    { value: 'touba_senegal', label: 'Touba, Senegal' },
    { value: 'bamako_mali', label: 'Bamako, Mali' },
    { value: 'ouagadougou_burkina_faso', label: 'Ouagadougou, Burkina Faso' },
    { value: 'niamey_niger', label: 'Niamey, Niger' },
    { value: 'lome_togo', label: 'Lomé, Togo' },
    { value: 'cotonou_benin', label: 'Cotonou, Benin' },
  
    // AFRICA - East Africa
    { value: 'addis_ababa_ethiopia', label: 'Addis Ababa, Ethiopia' },
    { value: 'dire_dawa_ethiopia', label: 'Dire Dawa, Ethiopia' },
    { value: 'nairobi_kenya', label: 'Nairobi, Kenya' },
    { value: 'mombasa_kenya', label: 'Mombasa, Kenya' },
    { value: 'kampala_uganda', label: 'Kampala, Uganda' },
    { value: 'gulu_uganda', label: 'Gulu, Uganda' },
    { value: 'dar_es_salaam_tanzania', label: 'Dar es Salaam, Tanzania' },
    { value: 'mwanza_tanzania', label: 'Mwanza, Tanzania' },
    { value: 'kigali_rwanda', label: 'Kigali, Rwanda' },
    { value: 'mogadishu_somalia', label: 'Mogadishu, Somalia' },
    { value: 'hargeisa_somalia', label: 'Hargeisa, Somalia' },
    { value: 'juba_south_sudan', label: 'Juba, South Sudan' },
  
    // AFRICA - Central Africa
    { value: 'kinshasa_congo_drc', label: 'Kinshasa, Congo (DRC)' },
    { value: 'lubumbashi_congo_drc', label: 'Lubumbashi, Congo (DRC)' },
    { value: 'douala_cameroon', label: 'Douala, Cameroon' },
    { value: 'yaounde_cameroon', label: 'Yaoundé, Cameroon' },
    { value: 'libreville_gabon', label: 'Libreville, Gabon' },
    { value: 'malabo_equatorial_guinea', label: 'Malabo, Equatorial Guinea' },
    { value: 'bangui_central_african_republic', label: 'Bangui, Central African Republic' },
    { value: 'n_djamena_chad', label: 'N’Djamena, Chad' },
  
    // AFRICA - Southern Africa
    { value: 'johannesburg_south_africa', label: 'Johannesburg, South Africa' },
    { value: 'cape_town_south_africa', label: 'Cape Town, South Africa' },
    { value: 'durban_south_africa', label: 'Durban, South Africa' },
    { value: 'luanda_angola', label: 'Luanda, Angola' },
    { value: 'maputo_mozambique', label: 'Maputo, Mozambique' },
    { value: 'lusaka_zambia', label: 'Lusaka, Zambia' },
    { value: 'ndola_zambia', label: 'Ndola, Zambia' },
    { value: 'harare_zimbabwe', label: 'Harare, Zimbabwe' },
    { value: 'bulawayo_zimbabwe', label: 'Bulawayo, Zimbabwe' },
    { value: 'gaborone_botswana', label: 'Gaborone, Botswana' },
    { value: 'windhoek_namibia', label: 'Windhoek, Namibia' },
    { value: 'mbabane_eswatini', label: 'Mbabane, Eswatini' },
  
    // SOUTH AMERICA
    { value: 'buenos_aires_argentina', label: 'Buenos Aires, Argentina' },
    { value: 'cordoba_argentina', label: 'Córdoba, Argentina' },
    { value: 'rosario_argentina', label: 'Rosario, Argentina' },
    { value: 'la_paz_bolivia', label: 'La Paz, Bolivia' },
    { value: 'sucre_bolivia', label: 'Sucre, Bolivia' },
    { value: 'sao_paulo_brazil', label: 'São Paulo, Brazil' },
    { value: 'rio_de_janeiro_brazil', label: 'Rio de Janeiro, Brazil' },
    { value: 'brasilia_brazil', label: 'Brasília, Brazil' },
    { value: 'salvador_brazil', label: 'Salvador, Brazil' },
    { value: 'santiago_chile', label: 'Santiago, Chile' },
    { value: 'valparaiso_chile', label: 'Valparaíso, Chile' },
    { value: 'bogota_colombia', label: 'Bogotá, Colombia' },
    { value: 'medellin_colombia', label: 'Medellín, Colombia' },
    { value: 'cali_colombia', label: 'Cali, Colombia' },
    { value: 'quito_ecuador', label: 'Quito, Ecuador' },
    { value: 'guayaquil_ecuador', label: 'Guayaquil, Ecuador' },
    { value: 'lima_peru', label: 'Lima, Peru' },
    { value: 'arequipa_peru', label: 'Arequipa, Peru' },
    { value: 'asuncion_paraguay', label: 'Asunción, Paraguay' },
    { value: 'montevideo_uruguay', label: 'Montevideo, Uruguay' },
    { value: 'caracas_venezuela', label: 'Caracas, Venezuela' },
    { value: 'maracaibo_venezuela', label: 'Maracaibo, Venezuela' },
  
    // EUROPE
    { value: 'london_uk', label: 'London, UK' },
    { value: 'manchester_uk', label: 'Manchester, UK' },
    { value: 'birmingham_uk', label: 'Birmingham, UK' },
    { value: 'paris_france', label: 'Paris, France' },
    { value: 'marseille_france', label: 'Marseille, France' },
    { value: 'lyon_france', label: 'Lyon, France' },
    { value: 'berlin_germany', label: 'Berlin, Germany' },
    { value: 'munich_germany', label: 'Munich, Germany' },
    { value: 'hamburg_germany', label: 'Hamburg, Germany' },
    { value: 'rome_italy', label: 'Rome, Italy' },
    { value: 'milan_italy', label: 'Milan, Italy' },
    { value: 'naples_italy', label: 'Naples, Italy' },
    { value: 'madrid_spain', label: 'Madrid, Spain' },
    { value: 'barcelona_spain', label: 'Barcelona, Spain' },
    { value: 'valencia_spain', label: 'Valencia, Spain' },
    { value: 'lisbon_portugal', label: 'Lisbon, Portugal' },
    { value: 'porto_portugal', label: 'Porto, Portugal' },
    { value: 'amsterdam_netherlands', label: 'Amsterdam, Netherlands' },
    { value: 'rotterdam_netherlands', label: 'Rotterdam, Netherlands' },
    { value: 'brussels_belgium', label: 'Brussels, Belgium' },
    { value: 'antwerp_belgium', label: 'Antwerp, Belgium' },
    { value: 'zurich_switzerland', label: 'Zurich, Switzerland' },
    { value: 'geneva_switzerland', label: 'Geneva, Switzerland' },
    { value: 'vienna_austria', label: 'Vienna, Austria' },
    { value: 'salzburg_austria', label: 'Salzburg, Austria' },
    { value: 'stockholm_sweden', label: 'Stockholm, Sweden' },
    { value: 'malmo_sweden', label: 'Malmö, Sweden' },
    { value: 'copenhagen_denmark', label: 'Copenhagen, Denmark' },
    { value: 'oslo_norway', label: 'Oslo, Norway' },
    { value: 'helsinki_finland', label: 'Helsinki, Finland' },
    { value: 'tallinn_estonia', label: 'Tallinn, Estonia' },
    { value: 'riga_latvia', label: 'Riga, Latvia' },
    { value: 'vilnius_lithuania', label: 'Vilnius, Lithuania' },
    { value: 'warsaw_poland', label: 'Warsaw, Poland' },
    { value: 'krakow_poland', label: 'Krakow, Poland' },
    { value: 'prague_czech_republic', label: 'Prague, Czech Republic' },
    { value: 'bratislava_slovakia', label: 'Bratislava, Slovakia' },
    { value: 'budapest_hungary', label: 'Budapest, Hungary' },
    { value: 'ljubljana_slovenia', label: 'Ljubljana, Slovenia' },
    { value: 'zagreb_croatia', label: 'Zagreb, Croatia' },
    { value: 'belgrade_serbia', label: 'Belgrade, Serbia' },
    { value: 'sarajevo_bosnia_and_herzegovina', label: 'Sarajevo, Bosnia and Herzegovina' },
    { value: 'skopje_north_macedonia', label: 'Skopje, North Macedonia' },
    { value: 'tirana_albania', label: 'Tirana, Albania' },
    { value: 'bucharest_romania', label: 'Bucharest, Romania' },
    { value: 'sofia_bulgaria', label: 'Sofia, Bulgaria' },
    { value: 'athens_greece', label: 'Athens, Greece' },
    { value: 'thessaloniki_greece', label: 'Thessaloniki, Greece' },
    { value: 'nicosia_cyprus', label: 'Nicosia, Cyprus' },
    { value: 'valletta_malta', label: 'Valletta, Malta' },
  
    // NORTH AMERICA
    { value: 'new_york_usa', label: 'New York, USA' },
    { value: 'los_angeles_usa', label: 'Los Angeles, USA' },
    { value: 'chicago_usa', label: 'Chicago, USA' },
    { value: 'houston_usa', label: 'Houston, USA' },
    { value: 'phoenix_usa', label: 'Phoenix, USA' },
    { value: 'philadelphia_usa', label: 'Philadelphia, USA' },
    { value: 'san_antonio_usa', label: 'San Antonio, USA' },
    { value: 'san_diego_usa', label: 'San Diego, USA' },
    { value: 'dallas_usa', label: 'Dallas, USA' },
    { value: 'san_jose_usa', label: 'San Jose, USA' },
    { value: 'austin_usa', label: 'Austin, USA' },
    { value: 'jacksonville_usa', label: 'Jacksonville, USA' },
    { value: 'san_francisco_usa', label: 'San Francisco, USA' },
    { value: 'columbus_usa', label: 'Columbus, USA' },
    { value: 'indianapolis_usa', label: 'Indianapolis, USA' },
    { value: 'seattle_usa', label: 'Seattle, USA' },
    { value: 'denver_usa', label: 'Denver, USA' },
    { value: 'washington_dc_usa', label: 'Washington, D.C., USA' },
    { value: 'boston_usa', label: 'Boston, USA' },
    { value: 'nashville_usa', label: 'Nashville, USA' },
    { value: 'baltimore_usa', label: 'Baltimore, USA' },
    { value: 'louisville_usa', label: 'Louisville, USA' },
    { value: 'milwaukee_usa', label: 'Milwaukee, USA' },
    { value: 'portland_usa', label: 'Portland, USA' },
    { value: 'las_vegas_usa', label: 'Las Vegas, USA' },
    { value: 'toronto_canada', label: 'Toronto, Canada' },
    { value: 'montreal_canada', label: 'Montreal, Canada' },
    { value: 'vancouver_canada', label: 'Vancouver, Canada' },
    { value: 'calgary_canada', label: 'Calgary, Canada' },
    { value: 'edmonton_canada', label: 'Edmonton, Canada' },
    { value: 'ottawa_canada', label: 'Ottawa, Canada' },
    { value: 'quebec_city_canada', label: 'Quebec City, Canada' },
    { value: 'winnipeg_canada', label: 'Winnipeg, Canada' },
    { value: 'mexico_city_mexico', label: 'Mexico City, Mexico' },
    { value: 'guadalajara_mexico', label: 'Guadalajara, Mexico' },
    { value: 'monterrey_mexico', label: 'Monterrey, Mexico' },
    { value: 'tijuana_mexico', label: 'Tijuana, Mexico' },
    { value: 'cancun_mexico', label: 'Cancún, Mexico' },
  
    // OCEANIA
    { value: 'sydney_australia', label: 'Sydney, Australia' },
    { value: 'melbourne_australia', label: 'Melbourne, Australia' },
    { value: 'brisbane_australia', label: 'Brisbane, Australia' },
    { value: 'perth_australia', label: 'Perth, Australia' },
    { value: 'adelaide_australia', label: 'Adelaide, Australia' },
    { value: 'canberra_australia', label: 'Canberra, Australia' },
    { value: 'hobart_australia', label: 'Hobart, Australia' },
    { value: 'auckland_new_zealand', label: 'Auckland, New Zealand' },
    { value: 'wellington_new_zealand', label: 'Wellington, New Zealand' },
    { value: 'christchurch_new_zealand', label: 'Christchurch, New Zealand' },
    { value: 'suva_fiji', label: 'Suva, Fiji' },
    { value: 'port_moresby_papua_new_guinea', label: 'Port Moresby, Papua New Guinea' },
    { value: 'honiara_solomon_islands', label: 'Honiara, Solomon Islands' },
    { value: 'nuku_alofa_tonga', label: 'Nukuʻalofa, Tonga' },
    { value: 'apia_samoa', label: 'Apia, Samoa' },
  
    // CARIBBEAN
    { value: 'havana_cuba', label: 'Havana, Cuba' },
    { value: 'santiago_de_cuba_cuba', label: 'Santiago de Cuba, Cuba' },
    { value: 'kingston_jamaica', label: 'Kingston, Jamaica' },
    { value: 'montego_bay_jamaica', label: 'Montego Bay, Jamaica' },
    { value: 'santo_domingo_dominican_republic', label: 'Santo Domingo, Dominican Republic' },
    { value: 'santiago_de_los_caballeros_dominican_republic', label: 'Santiago de los Caballeros, Dominican Republic' },
    { value: 'port_au_prince_haiti', label: 'Port-au-Prince, Haiti' },
    { value: 'nassau_bahamas', label: 'Nassau, Bahamas' },
    { value: 'bridgetown_barbados', label: 'Bridgetown, Barbados' },
    { value: 'castries_saint_lucia', label: 'Castries, Saint Lucia' },
    { value: 'kingstown_saint_vincent_and_the_grenadines', label: 'Kingstown, Saint Vincent and the Grenadines' },
    { value: 'st_john_s_antigua_and_barbuda', label: 'St. John’s, Antigua and Barbuda' },
    { value: 'roseau_dominica', label: 'Roseau, Dominica' },
    { value: 'basseterre_saint_kitts_and_nevis', label: 'Basseterre, Saint Kitts and Nevis' },
  
    // CENTRAL ASIA
    { value: 'almaty_kazakhstan', label: 'Almaty, Kazakhstan' },
    { value: 'nur_sultan_kazakhstan', label: 'Nur-Sultan, Kazakhstan' },
    { value: 'tashkent_uzbekistan', label: 'Tashkent, Uzbekistan' },
    { value: 'samarkand_uzbekistan', label: 'Samarkand, Uzbekistan' },
    { value: 'bishkek_kyrgyzstan', label: 'Bishkek, Kyrgyzstan' },
    { value: 'osh_kyrgyzstan', label: 'Osh, Kyrgyzstan' },
    { value: 'dushanbe_tajikistan', label: 'Dushanbe, Tajikistan' },
    { value: 'khujand_tajikistan', label: 'Khujand, Tajikistan' },
    { value: 'ashgabat_turkmenistan', label: 'Ashgabat, Turkmenistan' },
  
    // MIDDLE EAST
    { value: 'tehran_iran', label: 'Tehran, Iran' },
    { value: 'mashhad_iran', label: 'Mashhad, Iran' },
    { value: 'baghdad_iraq', label: 'Baghdad, Iraq' },
    { value: 'basra_iraq', label: 'Basra, Iraq' },
    { value: 'beirut_lebanon', label: 'Beirut, Lebanon' },
    { value: 'tripoli_lebanon', label: 'Tripoli, Lebanon' },
    { value: 'damascus_syria', label: 'Damascus, Syria' },
    { value: 'aleppo_syria', label: 'Aleppo, Syria' },
    { value: 'amman_jordan', label: 'Amman, Jordan' },
    { value: 'zarqa_jordan', label: 'Zarqa, Jordan' },
    { value: 'sana_a_yemen', label: 'Sana’a, Yemen' },
    { value: 'aden_yemen', label: 'Aden, Yemen' },
  
    // Additional Cities (to reach ~1000, continuing the pattern)
    // ASIA - Southeast Asia (more)
    { value: 'palembang_indonesia', label: 'Palembang, Indonesia' },
    { value: 'semarang_indonesia', label: 'Semarang, Indonesia' },
    { value: 'hat_yai_thailand', label: 'Hat Yai, Thailand' },
    { value: 'khon_kaen_thailand', label: 'Khon Kaen, Thailand' },
    { value: 'johor_bahru_malaysia', label: 'Johor Bahru, Malaysia' },
    { value: 'ipoh_malaysia', label: 'Ipoh, Malaysia' },
    { value: 'haiphong_vietnam', label: 'Haiphong, Vietnam' },
    { value: 'bien_hoa_vietnam', label: 'Bien Hoa, Vietnam' },
    { value: 'quezon_city_philippines', label: 'Quezon City, Philippines' },
    { value: 'baguio_philippines', label: 'Baguio, Philippines' },
    { value: 'yangon_myanmar', label: 'Yangon, Myanmar' },
    { value: 'battambang_cambodia', label: 'Battambang, Cambodia' },
    { value: 'siem_reap_cambodia', label: 'Siem Reap, Cambodia' },
    { value: 'savannakhet_laos', label: 'Savannakhet, Laos' },
  
    // ASIA - South Asia (more)
    { value: 'khulna_bangladesh', label: 'Khulna, Bangladesh' },
    { value: 'comilla_bangladesh', label: 'Comilla, Bangladesh' },
    { value: 'ahmedabad_india', label: 'Ahmedabad, India' },
    { value: 'hyderabad_india', label: 'Hyderabad, India' },
    { value: 'kanpur_india', label: 'Kanpur, India' },
    { value: 'patna_india', label: 'Patna, India' },
    { value: 'bhopal_india', label: 'Bhopal, India' },
    { value: 'lahore_pakistan', label: 'Lahore, Pakistan' },
    { value: 'peshawar_pakistan', label: 'Peshawar, Pakistan' },
    { value: 'quetta_pakistan', label: 'Quetta, Pakistan' },
    { value: 'colombo_sri_lanka', label: 'Colombo, Sri Lanka' },
    { value: 'biratnagar_nepal', label: 'Biratnagar, Nepal' },
    { value: 'dharan_nepal', label: 'Dharan, Nepal' },
  
    // ASIA - East Asia (more)
    { value: 'nagoya_japan', label: 'Nagoya, Japan' },
    { value: 'kobe_japan', label: 'Kobe, Japan' },
    { value: 'nanjing_china', label: 'Nanjing, China' },
    { value: 'qingdao_china', label: 'Qingdao, China' },
    { value: 'wuhan_china', label: 'Wuhan, China' },
    { value: 'taichung_taiwan', label: 'Taichung, Taiwan' },
    { value: 'daegu_south_korea', label: 'Daegu, South Korea' },
    { value: 'gwangju_south_korea', label: 'Gwangju, South Korea' },
    { value: 'choibalsan_mongolia', label: 'Choibalsan, Mongolia' },
  
    // AFRICA - North Africa (more)
    { value: 'port_said_egypt', label: 'Port Said, Egypt' },
    { value: 'suez_egypt', label: 'Suez, Egypt' },
    { value: 'fes_morocco', label: 'Fes, Morocco' },
    { value: 'sale_morocco', label: 'Salé, Morocco' },
    { value: 'annaba_algeria', label: 'Annaba, Algeria' },
    { value: 'tlemcen_algeria', label: 'Tlemcen, Algeria' },
    { value: 'gabes_tunisia', label: 'Gabès, Tunisia' },
    { value: 'bizerte_tunisia', label: 'Bizerte, Tunisia' },
    { value: 'wad_medani_sudan', label: 'Wad Medani, Sudan' },
  
    // AFRICA - West Africa (more)
    { value: 'kano_nigeria', label: 'Kano, Nigeria' },
    { value: 'port_harcourt_nigeria', label: 'Port Harcourt, Nigeria' },
    { value: 'tamale_ghana', label: 'Tamale, Ghana' },
    { value: 'san_pedro_ivory_coast', label: 'San-Pédro, Ivory Coast' },
    { value: 'kaolack_senegal', label: 'Kaolack, Senegal' },
    { value: 'segu_mali', label: 'Ségu, Mali' },
    { value: 'banfora_burkina_faso', label: 'Banfora, Burkina Faso' },
    { value: 'zinder_niger', label: 'Zinder, Niger' },
    { value: 'porto_novo_benin', label: 'Porto-Novo, Benin' },
    { value: 'parakou_benin', label: 'Parakou, Benin' },
    { value: 'monrovia_liberia', label: 'Monrovia, Liberia' },
    { value: 'freetown_sierra_leone', label: 'Freetown, Sierra Leone' },
  
    // AFRICA - East Africa (more)
    { value: 'bahir_dar_ethiopia', label: 'Bahir Dar, Ethiopia' },
    { value: 'hawassa_ethiopia', label: 'Hawassa, Ethiopia' },
    { value: 'kisumu_kenya', label: 'Kisumu, Kenya' },
    { value: 'nakuru_kenya', label: 'Nakuru, Kenya' },
    { value: 'mbale_uganda', label: 'Mbale, Uganda' },
    { value: 'arusha_tanzania', label: 'Arusha, Tanzania' },
    { value: 'dodoma_tanzania', label: 'Dodoma, Tanzania' },
    { value: 'butare_rwanda', label: 'Butare, Rwanda' },
    { value: 'garowe_somalia', label: 'Garowe, Somalia' },
    { value: 'wau_south_sudan', label: 'Wau, South Sudan' },
    { value: 'moroni_comoros', label: 'Moroni, Comoros' },
    { value: 'antananarivo_madagascar', label: 'Antananarivo, Madagascar' },
  
    // AFRICA - Central Africa (more)
    { value: 'mbuji_mayi_congo_drc', label: 'Mbuji-Mayi, Congo (DRC)' },
    { value: 'kisangani_congo_drc', label: 'Kisangani, Congo (DRC)' },
    { value: 'garoua_cameroon', label: 'Garoua, Cameroon' },
    { value: 'port_gentil_gabon', label: 'Port-Gentil, Gabon' },
    { value: 'oyem_gabon', label: 'Oyem, Gabon' },
    { value: 'brazzaville_congo', label: 'Brazzaville, Congo' },
    { value: 'pointe_noire_congo', label: 'Pointe-Noire, Congo' },
  
    // AFRICA - Southern Africa (more)
    { value: 'pretoria_south_africa', label: 'Pretoria, South Africa' },
    { value: 'bloemfontein_south_africa', label: 'Bloemfontein, South Africa' },
    { value: 'huambo_angola', label: 'Huambo, Angola' },
    { value: 'lobito_angola', label: 'Lobito, Angola' },
    { value: 'beira_mozambique', label: 'Beira, Mozambique' },
    { value: 'nampula_mozambique', label: 'Nampula, Mozambique' },
    { value: 'kitwe_zambia', label: 'Kitwe, Zambia' },
    { value: 'gweru_zimbabwe', label: 'Gweru, Zimbabwe' },
    { value: 'francistown_botswana', label: 'Francistown, Botswana' },
    { value: 'walvis_bay_namibia', label: 'Walvis Bay, Namibia' },
    { value: 'manzini_eswatini', label: 'Manzini, Eswatini' },
  
    // SOUTH AMERICA (more)
    { value: 'mendoza_argentina', label: 'Mendoza, Argentina' },
    { value: 'la_plata_argentina', label: 'La Plata, Argentina' },
    { value: 'oruro_bolivia', label: 'Oruro, Bolivia' },
    { value: 'potosi_bolivia', label: 'Potosí, Bolivia' },
    { value: 'belo_horizonte_brazil', label: 'Belo Horizonte, Brazil' },
    { value: 'curitiba_brazil', label: 'Curitiba, Brazil' },
    { value: 'recife_brazil', label: 'Recife, Brazil' },
    { value: 'concepcion_chile', label: 'Concepción, Chile' },
    { value: 'antofagasta_chile', label: 'Antofagasta, Chile' },
    { value: 'cartagena_colombia', label: 'Cartagena, Colombia' },
    { value: 'barranquilla_colombia', label: 'Barranquilla, Colombia' },
    { value: 'loja_ecuador', label: 'Loja, Ecuador' },
    { value: 'trujillo_peru', label: 'Trujillo, Peru' },
    { value: 'cusco_peru', label: 'Cusco, Peru' },
    { value: 'encarnacion_paraguay', label: 'Encarnación, Paraguay' },
    { value: 'paysandu_uruguay', label: 'Paysandú, Uruguay' },
    { value: 'valencia_venezuela', label: 'Valencia, Venezuela' },
  
    // EUROPE (more)
    { value: 'liverpool_uk', label: 'Liverpool, UK' },
    { value: 'glasgow_uk', label: 'Glasgow, UK' },
    { value: 'toulouse_france', label: 'Toulouse, France' },
    { value: 'strasbourg_france', label: 'Strasbourg, France' },
    { value: 'frankfurt_germany', label: 'Frankfurt, Germany' },
    { value: 'cologne_germany', label: 'Cologne, Germany' },
    { value: 'turin_italy', label: 'Turin, Italy' },
    { value: 'palermo_italy', label: 'Palermo, Italy' },
    { value: 'seville_spain', label: 'Seville, Spain' },
    { value: 'zaragoza_spain', label: 'Zaragoza, Spain' },
    { value: 'coimbra_portugal', label: 'Coimbra, Portugal' },
    { value: 'utrecht_netherlands', label: 'Utrecht, Netherlands' },
    { value: 'ghent_belgium', label: 'Ghent, Belgium' },
    { value: 'bern_switzerland', label: 'Bern, Switzerland' },
    { value: 'graz_austria', label: 'Graz, Austria' },
    { value: 'uppsala_sweden', label: 'Uppsala, Sweden' },
    { value: 'odense_denmark', label: 'Odense, Denmark' },
    { value: 'bergen_norway', label: 'Bergen, Norway' },
    { value: 'tampere_finland', label: 'Tampere, Finland' },
    { value: 'tartu_estonia', label: 'Tartu, Estonia' },
    { value: 'daugavpils_latvia', label: 'Daugavpils, Latvia' },
    { value: 'kaunas_lithuania', label: 'Kaunas, Lithuania' },
    { value: 'wroclaw_poland', label: 'Wroclaw, Poland' },
    { value: 'brno_czech_republic', label: 'Brno, Czech Republic' },
    { value: 'kosice_slovakia', label: 'Košice, Slovakia' },
    { value: 'debrecen_hungary', label: 'Debrecen, Hungary' },
    { value: 'split_croatia', label: 'Split, Croatia' },
    { value: 'podgorica_montenegro', label: 'Podgorica, Montenegro' },
    { value: 'prishtina_kosovo', label: 'Prishtina, Kosovo' },
  
    // NORTH AMERICA (more)
    { value: 'miami_usa', label: 'Miami, USA' },
    { value: 'atlanta_usa', label: 'Atlanta, USA' },
    { value: 'orlando_usa', label: 'Orlando, USA' },
    { value: 'raleigh_usa', label: 'Raleigh, USA' },
    { value: 'charlotte_usa', label: 'Charlotte, USA' },
    { value: 'pittsburgh_usa', label: 'Pittsburgh, USA' },
    { value: 'cincinnati_usa', label: 'Cincinnati, USA' },
    { value: 'tucson_usa', label: 'Tucson, USA' },
    { value: 'sacramento_usa', label: 'Sacramento, USA' },
    { value: 'kansas_city_usa', label: 'Kansas City, USA' },
    { value: 'halifax_canada', label: 'Halifax, Canada' },
    { value: 'regina_canada', label: 'Regina, Canada' },
    { value: 'leon_mexico', label: 'León, Mexico' },
    { value: 'puebla_mexico', label: 'Puebla, Mexico' },
    { value: 'juarez_mexico', label: 'Juárez, Mexico' },
  
    // OCEANIA (more)
    { value: 'gold_coast_australia', label: 'Gold Coast, Australia' },
    { value: 'newcastle_australia', label: 'Newcastle, Australia' },
    { value: 'wollongong_australia', label: 'Wollongong, Australia' },
    { value: 'dunedin_new_zealand', label: 'Dunedin, New Zealand' },
    { value: 'hamilton_new_zealand', label: 'Hamilton, New Zealand' },
    { value: 'nadi_fiji', label: 'Nadi, Fiji' },
    { value: 'lae_papua_new_guinea', label: 'Lae, Papua New Guinea' },
    { value: 'port_vila_vanuatu', label: 'Port Vila, Vanuatu' },
  
    // CARIBBEAN (more)
    { value: 'camaguey_cuba', label: 'Camagüey, Cuba' },
    { value: 'spanish_town_jamaica', label: 'Spanish Town, Jamaica' },
    { value: 'puerto_plata_dominican_republic', label: 'Puerto Plata, Dominican Republic' },
    { value: 'les_cayes_haiti', label: 'Les Cayes, Haiti' },
    { value: 'freeport_bahamas', label: 'Freeport, Bahamas' },
    { value: 'georgetown_guyana', label: 'Georgetown, Guyana' },
    { value: 'paramaribo_suriname', label: 'Paramaribo, Suriname' },
  
    // CENTRAL ASIA (more)
    { value: 'aktobe_kazakhstan', label: 'Aktobe, Kazakhstan' },
    { value: 'pavlodar_kazakhstan', label: 'Pavlodar, Kazakhstan' },
    { value: 'namangan_uzbekistan', label: 'Namangan, Uzbekistan' },
    { value: 'fergana_uzbekistan', label: 'Fergana, Uzbekistan' },
    { value: 'tokmok_kyrgyzstan', label: 'Tokmok, Kyrgyzstan' },
    { value: 'khorugh_tajikistan', label: 'Khorugh, Tajikistan' },
    { value: 'turkmenabat_turkmenistan', label: 'Turkmenabat, Turkmenistan' },
  
    // MIDDLE EAST (more)
    { value: 'isfahan_iran', label: 'Isfahan, Iran' },
    { value: 'shiraz_iran', label: 'Shiraz, Iran' },
    { value: 'mosul_iraq', label: 'Mosul, Iraq' },
    { value: 'erbil_iraq', label: 'Erbil, Iraq' },
    { value: 'sidon_lebanon', label: 'Sidon, Lebanon' },
    { value: 'latakia_syria', label: 'Latakia, Syria' },
    { value: 'irbid_jordan', label: 'Irbid, Jordan' },
    { value: 'taiz_yemen', label: 'Taiz, Yemen' },
     { value: 'multan_pakistan', label: 'Multan, Pakistan' },
  { value: 'gujranwala_pakistan', label: 'Gujranwala, Pakistan' },
  { value: 'hyderabad_pakistan', label: 'Hyderabad, Pakistan' },
  { value: 'sargodha_pakistan', label: 'Sargodha, Pakistan' },
  { value: 'bahawalpur_pakistan', label: 'Bahawalpur, Pakistan' },
  { value: 'sukkur_pakistan', label: 'Sukkur, Pakistan' },
  { value: 'larkana_pakistan', label: 'Larkana, Pakistan' },
  { value: 'sheikhupura_pakistan', label: 'Sheikhupura, Pakistan' },
  { value: 'jhang_pakistan', label: 'Jhang, Pakistan' },
  { value: 'rahim_yar_khan_pakistan', label: 'Rahim Yar Khan, Pakistan' },
  { value: 'mardan_pakistan', label: 'Mardan, Pakistan' },
  { value: 'kasur_pakistan', label: 'Kasur, Pakistan' },
  { value: 'dera_ghazi_khan_pakistan', label: 'Dera Ghazi Khan, Pakistan' },
  { value: 'sahiwal_pakistan', label: 'Sahiwal, Pakistan' },
  { value: 'nawabshah_pakistan', label: 'Nawabshah, Pakistan' },
  { value: 'mingora_pakistan', label: 'Mingora, Pakistan' },
  { value: 'okara_pakistan', label: 'Okara, Pakistan' },
  { value: 'mirpur_khas_pakistan', label: 'Mirpur Khas, Pakistan' },
  { value: 'chiniot_pakistan', label: 'Chiniot, Pakistan' },
  { value: 'kamoke_pakistan', label: 'Kamoke, Pakistan' },
  { value: 'burewala_pakistan', label: 'Burewala, Pakistan' },
  { value: 'jacobabad_pakistan', label: 'Jacobabad, Pakistan' },
  { value: 'khairpur_pakistan', label: 'Khairpur, Pakistan' },
  { value: 'kohat_pakistan', label: 'Kohat, Pakistan' },
  { value: 'daska_pakistan', label: 'Daska, Pakistan' },
  { value: 'mandi_bahauddin_pakistan', label: 'Mandi Bahauddin, Pakistan' },
  { value: 'ahmedpur_east_pakistan', label: 'Ahmedpur East, Pakistan' },
  { value: 'jhelum_pakistan', label: 'Jhelum, Pakistan' },
  { value: 'vehari_pakistan', label: 'Vehari, Pakistan' },
  { value: 'nowshera_pakistan', label: 'Nowshera, Pakistan' },
  { value: 'dadu_pakistan', label: 'Dadu, Pakistan' },
  { value: 'charsadda_pakistan', label: 'Charsadda, Pakistan' },
  { value: 'shikarpur_pakistan', label: 'Shikarpur, Pakistan' },
  { value: 'kandhkot_pakistan', label: 'Kandhkot, Pakistan' },
  { value: 'sanghar_pakistan', label: 'Sanghar, Pakistan' },
  { value: 'hafizabad_pakistan', label: 'Hafizabad, Pakistan' },
  { value: 'tando_allahyar_pakistan', label: 'Tando Allahyar, Pakistan' },
  { value: 'attock_pakistan', label: 'Attock, Pakistan' },
  { value: 'kot_addu_pakistan', label: 'Kot Addu, Pakistan' },
  { value: 'turbat_pakistan', label: 'Turbat, Pakistan' },
  { value: 'khuzdar_pakistan', label: 'Khuzdar, Pakistan' },
  { value: 'chaman_pakistan', label: 'Chaman, Pakistan' },
  { value: 'zhob_pakistan', label: 'Zhob, Pakistan' },
  { value: 'gwadar_pakistan', label: 'Gwadar, Pakistan' },
  { value: 'haripur_pakistan', label: 'Haripur, Pakistan' },
  { value: 'mansehra_pakistan', label: 'Mansehra, Pakistan' },
  { value: 'bannu_pakistan', label: 'Bannu, Pakistan' },
  { value: 'swabi_pakistan', label: 'Swabi, Pakistan' },
  { value: 'dera_ismail_khan_pakistan', label: 'Dera Ismail Khan, Pakistan' },
  { value: 'chitral_pakistan', label: 'Chitral, Pakistan' },
   { value: 'gujrat_pakistan', label: 'Gujrat, Pakistan' },
  { value: 'bahawalnagar_pakistan', label: 'Bahawalnagar, Pakistan' },
  { value: 'sadiqabad_pakistan', label: 'Sadiqabad, Pakistan' },
  { value: 'muzaffargarh_pakistan', label: 'Muzaffargarh, Pakistan' },
  { value: 'muridke_pakistan', label: 'Muridke, Pakistan' },
  { value: 'kamalia_pakistan', label: 'Kamalia, Pakistan' },
  { value: 'pakpattan_pakistan', label: 'Pakpattan, Pakistan' },
  { value: 'toba_tek_singh_pakistan', label: 'Toba Tek Singh, Pakistan' },
  { value: 'chistian_pakistan', label: 'Chistian, Pakistan' },
  { value: 'jaranwala_pakistan', label: 'Jaranwala, Pakistan' },
  { value: 'ahmadpur_sial_pakistan', label: 'Ahmadpur Sial, Pakistan' },
  { value: 'vohari_pakistan', label: 'Vohari, Pakistan' },
  { value: 'bhalwal_pakistan', label: 'Bhalwal, Pakistan' },
  { value: 'dipalpur_pakistan', label: 'Dipalpur, Pakistan' },
  { value: 'taunsa_sharif_pakistan', label: 'Taunsa Sharif, Pakistan' },
  { value: 'kot_momin_pakistan', label: 'Kot Momin, Pakistan' },
  { value: 'gojra_pakistan', label: 'Gojra, Pakistan' },
  { value: 'fateh_jang_pakistan', label: 'Fateh Jang, Pakistan' },
  { value: 'haroonabad_pakistan', label: 'Haroonabad, Pakistan' },
  { value: 'shorkot_pakistan', label: 'Shorkot, Pakistan' },
  { value: 'jamshoro_pakistan', label: 'Jamshoro, Pakistan' },
  { value: 'thatta_pakistan', label: 'Thatta, Pakistan' },
  { value: 'badin_pakistan', label: 'Badin, Pakistan' },
  { value: 'umerkot_pakistan', label: 'Umerkot, Pakistan' },
  { value: 'tando_muhammad_khan_pakistan', label: 'Tando Muhammad Khan, Pakistan' },
  { value: 'moro_pakistan', label: 'Moro, Pakistan' },
  { value: 'sehwan_pakistan', label: 'Sehwan, Pakistan' },
  { value: 'sangla_hill_pakistan', label: 'Sangla Hill, Pakistan' },
  { value: 'shahdadpur_pakistan', label: 'Shahdadpur, Pakistan' },
  { value: 'tando_adam_pakistan', label: 'Tando Adam, Pakistan' },
  { value: 'matli_pakistan', label: 'Matli, Pakistan' },
  { value: 'ghotki_pakistan', label: 'Ghotki, Pakistan' },
  { value: 'mirpur_mathelo_pakistan', label: 'Mirpur Mathelo, Pakistan' },
  { value: 'daharki_pakistan', label: 'Daharki, Pakistan' },
  { value: 'kamber_ali_khan_pakistan', label: 'Kamber Ali Khan, Pakistan' },
  { value: 'ratodero_pakistan', label: 'Ratodero, Pakistan' },
  { value: 'shahdadkot_pakistan', label: 'Shahdadkot, Pakistan' },
  { value: 'nawabshah_pakistan', label: 'Nawabshah, Pakistan' },
  { value: 'sibi_pakistan', label: 'Sibi, Pakistan' },
  { value: 'mastung_pakistan', label: 'Mastung, Pakistan' },
  { value: 'loralai_pakistan', label: 'Loralai, Pakistan' },
  { value: 'duki_pakistan', label: 'Duki, Pakistan' },
  { value: 'pishin_pakistan', label: 'Pishin, Pakistan' },
  { value: 'chagai_pakistan', label: 'Chagai, Pakistan' },
  { value: 'nushki_pakistan', label: 'Nushki, Pakistan' },
  { value: 'kalat_pakistan', label: 'Kalat, Pakistan' },
  { value: 'lasbela_pakistan', label: 'Lasbela, Pakistan' },
  { value: 'awaran_pakistan', label: 'Awaran, Pakistan' },
  { value: 'panjgur_pakistan', label: 'Panjgur, Pakistan' },
  { value: 'ketch_pakistan', label: 'Ketch, Pakistan' },
  { value: 'abbottabad_pakistan', label: 'Abbottabad, Pakistan' },
  { value: 'swat_pakistan', label: 'Swat, Pakistan' },
  { value: 'malakand_pakistan', label: 'Malakand, Pakistan' },
  { value: 'dir_pakistan', label: 'Dir, Pakistan' },
  { value: 'buner_pakistan', label: 'Buner, Pakistan' },
  { value: 'shangla_pakistan', label: 'Shangla, Pakistan' },
  { value: 'kohistan_pakistan', label: 'Kohistan, Pakistan' },
  { value: 'battagram_pakistan', label: 'Battagram, Pakistan' },
  { value: 'torghar_pakistan', label: 'Torghar, Pakistan' },
  { value: 'hangu_pakistan', label: 'Hangu, Pakistan' },
  { value: 'karak_pakistan', label: 'Karak, Pakistan' },
  { value: 'lakki_marwat_pakistan', label: 'Lakki Marwat, Pakistan' },
  { value: 'tank_pakistan', label: 'Tank, Pakistan' },
  { value: 'north_waziristan_pakistan', label: 'North Waziristan, Pakistan' },
  { value: 'south_waziristan_pakistan', label: 'South Waziristan, Pakistan' },
  { value: 'bajaur_pakistan', label: 'Bajaur, Pakistan' },
  { value: 'mohmand_pakistan', label: 'Mohmand, Pakistan' },
  { value: 'khyber_pakistan', label: 'Khyber, Pakistan' },
  { value: 'orakzai_pakistan', label: 'Orakzai, Pakistan' },
  { value: 'kurram_pakistan', label: 'Kurram, Pakistan' },
  { value: 'skardu_pakistan', label: 'Skardu, Pakistan' },
  { value: 'gilgit_pakistan', label: 'Gilgit, Pakistan' },
  { value: 'hunza_pakistan', label: 'Hunza, Pakistan' },
  { value: 'nagar_pakistan', label: 'Nagar, Pakistan' },
  { value: 'ghizer_pakistan', label: 'Ghizer, Pakistan' },
  { value: 'astor_pakistan', label: 'Astor, Pakistan' },
  { value: 'shigar_pakistan', label: 'Shigar, Pakistan' },
  { value: 'kharmang_pakistan', label: 'Kharmang, Pakistan' },
  { value: 'gupis_yasin_pakistan', label: 'Gupis-Yasin, Pakistan' },
  { value: 'muzaffarabad_pakistan', label: 'Muzaffarabad, Pakistan' },
  { value: 'mirpur_pakistan', label: 'Mirpur, Pakistan' },
  { value: 'bhimber_pakistan', label: 'Bhimber, Pakistan' },
  { value: 'kotli_pakistan', label: 'Kotli, Pakistan' },
  { value: 'bagh_pakistan', label: 'Bagh, Pakistan' },
  { value: 'sudhanoti_pakistan', label: 'Sudhanoti, Pakistan' },
  { value: 'poonch_pakistan', label: 'Poonch, Pakistan' },
  { value: 'haveli_pakistan', label: 'Haveli, Pakistan' },
  { value: 'hattian_bala_pakistan', label: 'Hattian Bala, Pakistan' },
  { value: 'neelum_pakistan', label: 'Neelum, Pakistan' },
  { value: 'narowal_pakistan', label: 'Narowal, Pakistan' },
  { value: 'shakargarh_pakistan', label: 'Shakargarh, Pakistan' },
  { value: 'rajanpur_pakistan', label: 'Rajanpur, Pakistan' },
  { value: 'layyah_pakistan', label: 'Layyah, Pakistan' },
  { value: 'khushab_pakistan', label: 'Khushab, Pakistan' },
  { value: 'bhakkar_pakistan', label: 'Bhakkar, Pakistan' },
  { value: 'mianwali_pakistan', label: 'Mianwali, Pakistan' },
  { value: 'jauharabad_pakistan', label: 'Jauharabad, Pakistan' },
  { value: 'kabirwala_pakistan', label: 'Kabirwala, Pakistan' },
  { value: 'shujabad_pakistan', label: 'Shujabad, Pakistan' },
  { value: 'jalalpur_pirwala_pakistan', label: 'Jalalpur Pirwala, Pakistan' },

  // India - Additional Cities
  { value: 'kanpur_india', label: 'Kanpur, India' },
  { value: 'lucknow_india', label: 'Lucknow, India' },
  { value: 'nagpur_india', label: 'Nagpur, India' },
  { value: 'indore_india', label: 'Indore, India' },
  { value: 'bhopal_india', label: 'Bhopal, India' },
  { value: 'patna_india', label: 'Patna, India' },
  { value: 'vadodara_india', label: 'Vadodara, India' },
  { value: 'coimbatore_india', label: 'Coimbatore, India' },
  { value: 'visakhapatnam_india', label: 'Visakhapatnam, India' },
  { value: 'agra_india', label: 'Agra, India' },
  { value: 'varanasi_india', label: 'Varanasi, India' },
  { value: 'madurai_india', label: 'Madurai, India' },
  { value: 'jodhpur_india', label: 'Jodhpur, India' },
  { value: 'raipur_india', label: 'Raipur, India' },
  { value: 'nashik_india', label: 'Nashik, India' },
  { value: 'faridabad_india', label: 'Faridabad, India' },
  { value: 'meerut_india', label: 'Meerut, India' },
  { value: 'rajkot_india', label: 'Rajkot, India' },
  { value: 'kalyan_dombivli_india', label: 'Kalyan-Dombivli, India' },
  { value: 'vasai_virar_india', label: 'Vasai-Virar, India' },
  { value: 'aurangabad_india', label: 'Aurangabad, India' },
  { value: 'dhanbad_india', label: 'Dhanbad, India' },
  { value: 'amritsar_india', label: 'Amritsar, India' },
  { value: 'jabalpur_india', label: 'Jabalpur, India' },
  { value: 'gwalior_india', label: 'Gwalior, India' },
  { value: 'vijayawada_india', label: 'Vijayawada, India' },
  { value: 'jamshedpur_india', label: 'Jamshedpur, India' },
  { value: 'durgapur_india', label: 'Durgapur, India' },
  { value: 'asansol_india', label: 'Asansol, India' },
  { value: 'rourkela_india', label: 'Rourkela, India' },
  { value: 'nanded_india', label: 'Nanded, India' },
  { value: 'kolhapur_india', label: 'Kolhapur, India' },
  { value: 'ajmer_india', label: 'Ajmer, India' },
  { value: 'akola_india', label: 'Akola, India' },
  { value: 'gulbarga_india', label: 'Gulbarga, India' },
  { value: 'jamnagar_india', label: 'Jamnagar, India' },
  { value: 'ujjain_india', label: 'Ujjain, India' },
  { value: 'loni_india', label: 'Loni, India' },
  { value: 'siliguri_india', label: 'Siliguri, India' },
  { value: 'jhansi_india', label: 'Jhansi, India' },
  { value: 'ulhasnagar_india', label: 'Ulhasnagar, India' },
  { value: 'jammu_india', label: 'Jammu, India' },
  { value: 'sangli_miraj_kupwad_india', label: 'Sangli-Miraj-Kupwad, India' },
  { value: 'mangalore_india', label: 'Mangalore, India' },
  { value: 'belgaum_india', label: 'Belgaum, India' },
  { value: 'ambattur_india', label: 'Ambattur, India' },
  { value: 'tirunelveli_india', label: 'Tirunelveli, India' },
  { value: 'malegaon_india', label: 'Malegaon, India' },
  { value: 'gaya_india', label: 'Gaya, India' },
  { value: 'jalgaon_india', label: 'Jalgaon, India' },
  { value: 'udaipur_india', label: 'Udaipur, India' },
  { value: 'maheshtala_india', label: 'Maheshtala, India' },
  { value: 'davanagere_india', label: 'Davanagere, India' },
  { value: 'kozhikode_india', label: 'Kozhikode, India' },
  { value: 'kurnool_india', label: 'Kurnool, India' },
  { value: 'rajpur_sonarpur_india', label: 'Rajpur Sonarpur, India' },
  { value: 'rajahmundry_india', label: 'Rajahmundry, India' },
  { value: 'bokaro_steel_city_india', label: 'Bokaro Steel City, India' },
  { value: 'south_dumdum_india', label: 'South Dumdum, India' },
  { value: 'bellary_india', label: 'Bellary, India' },
  { value: 'patiala_india', label: 'Patiala, India' },
  { value: 'gopalpur_india', label: 'Gopalpur, India' },
  { value: 'agartala_india', label: 'Agartala, India' },
  { value: 'bhagalpur_india', label: 'Bhagalpur, India' },
  { value: 'muzaffarnagar_india', label: 'Muzaffarnagar, India' },
  { value: 'bhatpara_india', label: 'Bhatpara, India' },
  { value: 'panihati_india', label: 'Panihati, India' },
  { value: 'latur_india', label: 'Latur, India' },
  { value: 'dhule_india', label: 'Dhule, India' },
  { value: 'tiruppur_india', label: 'Tiruppur, India' },
  { value: 'rohtak_india', label: 'Rohtak, India' },
  { value: 'korba_india', label: 'Korba, India' },
  { value: 'bhilwara_india', label: 'Bhilwara, India' },
  { value: 'berhampur_india', label: 'Berhampur, India' },
  { value: 'muzaffarpur_india', label: 'Muzaffarpur, India' },
  { value: 'ahmednagar_india', label: 'Ahmednagar, India' },
  { value: 'mathura_india', label: 'Mathura, India' },
  { value: 'kollam_india', label: 'Kollam, India' },
  { value: 'avadi_india', label: 'Avadi, India' },
  { value: 'kadapa_india', label: 'Kadapa, India' },
  { value: 'kamarhati_india', label: 'Kamarhati, India' },
  { value: 'sambalpur_india', label: 'Sambalpur, India' },
  { value: 'bilaspur_india', label: 'Bilaspur, India' },
  { value: 'shahjahanpur_india', label: 'Shahjahanpur, India' },
  { value: 'satna_india', label: 'Satna, India' },
  { value: 'bijapur_india', label: 'Bijapur, India' },
  { value: 'rampur_india', label: 'Rampur, India' },
  { value: 'shimoga_india', label: 'Shimoga, India' },
  { value: 'chandrapur_india', label: 'Chandrapur, India' },
  { value: 'junagadh_india', label: 'Junagadh, India' },
  { value: 'thrissur_india', label: 'Thrissur, India' },
  { value: 'alwar_india', label: 'Alwar, India' },
  { value: 'bardhaman_india', label: 'Bardhaman, India' },
  { value: 'kulti_india', label: 'Kulti, India' },
  { value: 'kakinada_india', label: 'Kakinada, India' },
  { value: 'nizamabad_india', label: 'Nizamabad, India' },
  { value: 'parbhani_india', label: 'Parbhani, India' },
  { value: 'tumkur_india', label: 'Tumkur, India' },
  { value: 'khammam_india', label: 'Khammam, India' },
  { value: 'uzhavoor_india', label: 'Uzhavoor, India' }
  
]